### ISSUE TITLE
Restructure Development documentation (Extbase / Fluid, core API, ...)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#10]
# Problem

* various place for viewhelpers (i[n Extbase / Fluid guide](https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Index.html)) and on [github in Fluid project](https://fluidtypo3.org/viewhelpers.html) (should be handled in #9 automatically, though)
*  2 book / guide for extbase / fluid
* Extbase / Fluid book often regarded as outdated
* other information missing
* various things in Wiki, some is outdated but some is partly relevant
* various pieces of information, needs homogenous structure
* general things for developers missing, some is in contrib guide (e.g. debug, setting up PhpStorm), could move to general "Developer Guide"

# Solution

... discuss possible solutions in comments

It would be important to decide on a **general structure for the development documenation**  and decide on structure for each manual (e.g. Core API).

**Comment by DanielSiepmann** [comment]
I would propose to add another solution. If we do not find someone to write it. We can create the repositories and move stuff around. As there are already references, we could merge them into a new Reference. While we merge the book and tutorial.

This might invite further contributions.

**Comment by sypets** [comment]
Actually, the reference might be Core API. So this is also an issue for Content Structure decisions.

**Comment by schams-net** [comment]
Initial plans for an "Extbase Development Tutorial" (exact project title to be determined) started already as discussed with @marble in May 2018. I am happy to take care of the management, coordination and authoring of this documentation. How this progresses over the next few months and if this tutorial replaces the existing [Extbase Fluid Guide](https://docs.typo3.org/typo3cms/ExtbaseGuide/) at one point needs to be seen. However, it definitely aims to do exactly this.

Having said that, the more information we can move to other documents, the better. This is in particular important for references, e.g. Fluid ViewHelpers, which can be generated automatically, and therefore always kept up-to-date.

A tutorial is not meant to describe all aspects and to provide all details, but to guide the reader to reach a specific goal. It is important that readers can get further from that point, or side-wise, e.g. get more details about ViewHelpers.

**Comment by sypets** [comment]
I changed the title for this issue. Here we can focus on the general structure. For actually writing new docs (e.g.  @schams-net project), we can create seperate issues.

**Comment by sypets** [comment]
Too big an issue to tackle right now and older than 2 years.
