### ISSUE TITLE
Mention of "Composer support"

### ISSUE THREAD

**Issue by Zillion01** [TYPO3-Documentation/T3DocTeam#103]
Hi!

What enables mention of "Composer support" at the TYPO3 repository for an extension?

![composer](https://user-images.githubusercontent.com/1055822/63932226-0ff21680-ca57-11e9-9864-51ac9f8b71d1.png)

My extension: https://extensions.typo3.org/extension/jpfaq/
composer req jvdp/jpfaq

thx

**Comment by sfsmfc** [comment]
![Bildschirmfoto 2019-08-31 um 20 02 46](https://user-images.githubusercontent.com/5294925/64067538-58adf900-cc2a-11e9-8bab-9df9a5eda527.png)

- Login into your account at [extensions.typo3.org](https://extensions.typo3.org)
- Go to `My Extensions`
- Edit your extension
- set the checkbox `I confirm the extension is published on https://packagist.org and I maintain the package`
- Add the composer name for your extensions

**Comment by Zillion01** [comment]
Thanks!!
