### ISSUE TITLE
Cleanup jobs for all manuals

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#11]
(check items, when done)

- [x] **_make**  folder should be absent 
* [ ] 1  **.gitignore** (same for all)
* [ ] 1 **Includes.rst.txt** (same for all)
  * [ ]  there are some differences, e.g. `role:: yaml(code)` in 
* [x] 1 **.editorconfig**, see #54
* [ ]  **Settings.cfg**
  * common stuff should be the same for all manuals)
  * add setting for YouTube
* [x] Included files should be named .rst.txt and not .rst
* [x]  For some manuals, the **README.rst** is missing, which will show some info on GitHub (at least the "Read online:" and "Repository" should be added. This is handled in #53
* [x] Add .github/CONTRIBUTING.rst : **Update**: this is handled in #50
* [x] **new**: remove `.. only:: html`: this is no longer necessary. Was used to exclude some things from generated PDF. Now we no longer create PDF. Still using this directive only complicates things for editors  - see  [Slack](https://typo3.slack.com/archives/C028JEPJL/p1559808137040900)

This must be done in all manuals and (some of it in all branches).

**Update (2018-01-05/Sybille):**

The basic files are documented in [Writing Documentation](https://docs.typo3.org/typo3cms/HowToDocument/GeneralConventions/DirectoryFilenames.html#information-about-basic-files). Because the files are displayed there with `literalincludes` from the same manual, it makes sense to keep the sample files there as well. We do not need additional templates, I think.

**Comment by nito-web** [comment]
Is there an example Repository with this files a clean version of the files you mentions and that we want to have "same for all"?

**Comment by DanielSiepmann** [comment]
Not yet, as far as I know.

But we already have https://github.com/TYPO3-Documentation/TYPO3CMS-Example-ExtensionManual which has to be adjusted.
It's already linked here: https://docs.typo3.org/typo3cms/GuidesAndTutorials/Index.html#example-manual

**Comment by sypets** [comment]
@nito-web If you have ideas, they are more than welcome

I self-assigned this and will look into it:

* what should be the content of the files (we already talked with Martin about some of it)
* where should master version of the file be hosted
* instead of maintaining this in each repo / branch, can some of these files be referenced from a central place

**Comment by sypets** [comment]
**Update (2019-01-05/Sybille)**: I think it is better to use the files in [Writing Documentation](https://docs.typo3.org/typo3cms/HowToDocument/) as templates, because they are [documented there](https://docs.typo3.org/typo3cms/HowToDocument/GeneralConventions/DirectoryFilenames.html#information-about-basic-files) and the contents of the file in that manual shown with `literalincludes`.

@marble Do you agree to use the files in this repository (T3DocTeam) as templates: Settings.cfg, Includes.txt, .editorconfig, .gitignore as mentioned in the first post of this thread? Are they up-to-date? Then we could already start using the files as blueprint and replace them where we see the necessity. 

I just ran into a repository where some things are missing in Settings.cfg and I'd like to use a state-of-the-art file as sample.

**Comment by sypets** [comment]
CONTRIBUTING.md is handled in #50, Readme.rst is handled in #53: done

**Comment by sypets** [comment]
.editorconfig handled in #54: done
