### ISSUE TITLE
Update TYPO3 API within dash and zeal

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/T3DocTeam#116]
Make up to date api.typo3.org available to these platforms:

* [ ] https://devdocs.io/
* [ ] https://zealdocs.org/
* [ ] https://kapeli.com/dash

zeal uses dash infrastructure, so adding it to dash should also add it to zeal.
Helpful documentation:
* https://kapeli.com/docsets#doxygen
* https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset

Internal references:
* https://github.com/TYPO3GmbH/doxygenapi
* https://bamboo.typo3.com/browse/TCA-DXC

**Comment by DanielSiepmann** [comment]
@mtelgkamp brought up this topic again.

As we already have updated api.typo3.org, this should be an task we can handle.

**Comment by linawolf** [comment]
We will replace api.typo3.org in a next step
