### ISSUE TITLE
Intercept: static redirects / broken links: sysext version redirect problem: e.g. rtehtmlarea

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#126]
Copied here from [Slack](https://typo3.slack.com/archives/C028JEPJL/p1577704375016600?thread_ts=1577485344.010800&cid=C028JEPJL):

Current problem:

1. rtehtmlarea redirect:
```
curl -I https://docs.typo3.org/typo3cms/extensions/rtehtmlarea/8.7.1/
...
location: https://docs.typo3.org/p/friendsoftypo3/rtehtmlarea/8.7/en-us.1/

```
2. cause of error: redirect (static):
```
# typo3/cms-rtehtmlarea
location ~ ^/typo3cms/extensions/rtehtmlarea/8.7(.*) {
    return 303 /p/friendsoftypo3/rtehtmlarea/8.7/en-us$1;
}
location ~ ^/typo3cms/extensions/rtehtmlarea/latest(.*) {
    return 303 /p/friendsoftypo3/rtehtmlarea/master/en-us$1;
}
location ~ ^/typo3cms/extensions/rtehtmlarea(/(?:(?!(7\.6|6\.2)).*))?$ {
    return 303 /p/friendsoftypo3/rtehtmlarea/master/en-us/$1;
}
```
https://bitbucket.typo3.com/projects/INT/repos/intercept/browse/config/nginx/redirects.conf

similar errors for cms-saltedpasswords, cms-rsaauth etc. ...

**Comment by sypets** [comment]
Created PR: https://bitbucket.typo3.com/projects/INT/repos/intercept/pull-requests/162/overview

**Comment by sypets** [comment]
Has been merged ... closing

**Comment by liayn** [comment]
Still seems to be a problem here:
https://typo3.slack.com/archives/C028JEPJL/p1585086167339800

**Comment by DanielSiepmann** [comment]
Thanks. I've created another PR to intercept with:

```
# Specific for "current" extension detail page in TER
location ~ ^/typo3cms/extensions/rtehtmlarea/8.7.2 {
    return 303 /p/friendsoftypo3/rtehtmlarea/8.7/en-us/;
}
```

Not fully sure whether there are still updates and we might need to make it more dynamic? I'm neither an nginx nor regex expert and therefore use more strict rules to not break anything.

**Comment by liayn** [comment]
@DanielSiepmann Yes there will be at least one more release!

`location ~ ^/typo3cms/extensions/rtehtmlarea/8\.7\.[0-9] {`

**Comment by liayn** [comment]
The manual is linked without a 404 now from TER, so I consider this solved.
