### ISSUE TITLE
SEO: Indexed, though blocked by robots.txt

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#130]
see google search console:

* URLs with _sources: https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/singlehtml/
* /singlehtml/, see #33
* [x] several "draft" pages (have been removed
* "dear project owner": https://docs.typo3.org/m/typo3/team-t3oteam/main/en-us/_buildinfo/DearProjectOwner.html
* ...

Using robots.txt alone is not a good mechanism to ensure that pages will not get indexed. (putting urls in robots.txt tells the search bot not to crawl them, however if they are linked to, they may be crawled and indexed, regardless).

Better:

* add HTTP header: `X-Robots-Tag`

or
* add `<meta name="robots" content="noindex,nofollow">` to HTML head

See

* https://support.google.com/webmasters/answer/93710?hl=en
* https://yoast.com/prevent-site-being-indexed/

**Comment by alexander-nitsche** [comment]
From current Slack conversation:

> Lina Wolf  6 days ago
> Can we do something to not index rst includes like https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/_sources/Functions/Stdwrap.rst.txt on Google?
> 
> Alexander Nitsche  6 days ago
> https://stackoverflow.com/questions/9052083/can-i-prevent-search-engines-from-indexing-an-entire-directory-on-my-website: Add
> User-agent: *
> Disallow: /_sources/
> to robots.txt.
> 
> Lina Wolf  6 days ago
> Yes, now where would we make a PR for the robots.rxr
> 
> Alexander Nitsche  6 days ago
> my first guess would be the rendering tool chain, which also creates the HTML and _sources folder etc.
> 
> Lina Wolf  5 days ago
> @martin.bless is it possible to edit the robots.txt?
> 
> Martin Bless  5 days ago
> This can only be solved directly on the server. There is only ONE robots.txt in the webroot folder that is respected, and it needs an explicite line for each folder you want to exclude. You cannot specify a wildcard for excluding folders, only a wildcard for excluding files. This being said, maybe a rule Disallow: *.rst.txtcould work. I don't know. One has to study the literature, for example https://developers.google.com/search/docs/advanced/robots/intro
> Don't forget that everything you do in this area is just the attempt to tell search enginges how you WOULD LIKE them to behave. They still can do whatever they want, and maybe even the opposite of what you told them. For example, the "View source" link already has the rel="no-follow"attribute. But, as you write, this didn't stop Google from following the link nevertheless.
> 
> Lina Wolf  5 days ago
> The rel="no-follow" on the link tells Google not to follow the link. However Google might have gotten there on another way by an external link, whatever.
> 
> Lina Wolf  5 days ago
> So It would really make sense to add it to the robots.txt
> 
> Martin Bless  5 days ago
> Yes, needs to be done in junction with deployment. Actually there is more that could be done. ① A find /var/www/webroot -type d -name _sourceswould tell you what needs to be added to the robots.txtfile. And, ② since quite a while, each single documentation has a _buildinfo/sitemap_files_html.txtfile, that lists, which files exactly would need to be taken into account to construct a Google Sitemap file. Lolli back then once had the idea to do so. Example: https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/_buildinfo/sitemap_files_html.txt

**Comment by sypets** [comment]
From my understanding, adding a URL to a robots.txt which is already indexed may not be enough to remove from index (if already indexed) (especially if the page is linked elsewhere). The robots.txt tells the crawler not to crawl. One source I found (from Google) even mentions that adding it in robots.txt may be counter productive - at least that is how it may be interpreted. 

Please also see my comment here: https://github.com/TYPO3-Documentation/T3DocTeam/issues/33#issuecomment-523365900

(Unfortunately, a lot of information out there is wrong and contradicts itself, so it is difficult to get a definitive answer for this).

I am no SEO expert but it would be good to get a SEO expert involved.

**Comment by linawolf** [comment]
We don't have anyone  who wants to work on this in long term unfortunately
