### ISSUE TITLE
Create a "latest" branch in addition to "master"?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#133]
# Motivation

How can we get changes added to documentation early? 

And be more clear and intuitive about the versions - what exactly is "master"?. 

# Problems:

* Currently the latest rendered branch is called "master". That is not very intuitive if someone is not doing core development. We used to call it "master (10-dev)"
* It is currently unclear what this represents: the current unreleased master (10.3) or the last release (10.2):  master would imply "unreleased master" but the current procedure is to change documentation, **after** a TYPO3 release, so current practice is as if "master" = "release". 

# Solutions:

* one possible solution might be to render the latest release as "latest" to point to latest release as default URL (instead of master)

branch   | URL       | version  | description
----------- | ----------- | ---------- | ---------------
master   | /master/ | 10.3-dev| development
latest      | /latest/   |  10.2      | latest release
9.5         | /9.5/       | 9.5         | no change here.

An alternative that "latest" represents the latest LTS release (this would currently be 9.5). In any case it is what should be considered the default version for TYPO3.

We should probably change the URLs in Settings.cfg and in the start pages to point to "latest" and not "master".

In any case, this is probably a little more work, but not too much. We could automate the branching out and changing in Settings.cfg.

# Related change

* to reduce the number of branches, I would not branch out minor branches (e.g. 10.1, 10.2). Create only one branch per major version (10). This is actually already current practice (though for 6.0, 6.1, 6.2 it was still done).

# Related

* #101 : version urls, e.g. /10/en-us >> /latest/en-us/ etc. (this is obsolete if this change is implemented)

**Comment by neufeind** [comment]
And also having /10.2/ as a working URL for that same /latest/ imho, so you can decide if you want to set links to a specific version (docs not chaning) or always the latest.

**Comment by sypets** [comment]
> And also having /10.2/ as a working URL for that same /latest/ imho, so you can decide if you want to set links to a specific version (docs not chaning) or always the latest.

However, we do not want to create too many branches (because that is more work with backporting). 

We could arrange a URLs` /10.2/ `but once 10.3 or 10.4 comes out that would just redirect there and I don't see an advantage because it rather adds to the confusion (having versions that point to a different version than advertised in the URL). 

I do think it would be cool though, to have a URL /10/ _now_ (a[s I already proposed](https://github.com/TYPO3-Documentation/T3DocTeam/issues/101)) which would always redirect to latest 10 now and in the future.

Previously, we created a branch per major.minor version (e.g. 6.0, 6.1, 6.2). We don't really do that any more. we branch out when the LTS (10.4) comes out. If another minor version is released after the LTS (e.g. 10.5), we could branch again (but I am hoping for just one branch per major version, actually).

I personally, don't think it makes sense to maintain documentation for TYPO3 versions that can be easily updated. 

The goal is to find a solution that is not tooo much more work than now, but better in clarity and offers what people need.

**Comment by neufeind** [comment]
I'm with you regarding 10 meaning "the latest 10" (10.1, 10.2, ...) until it finally becomes "the 10 LTS" might be a good idea imho, yes.
Basically this issue here was about "master" really meaning git-master/HEAD and not "the current LTS". Fine with that.

**Comment by DanielSiepmann** [comment]
I would like to close this. We decided to have `master` and it is part of the infrastructure, documentation, workflows and intercept.
Renaming that branch from master to latest does create work and would need further changes.

**Comment by sypets** [comment]
ok, closing, but can we at least clarify what master means? Is it the "latest release" (that would have been 10.3 a couple of days ago) or is it the same as "master" in the core? The choice influences how soon you can update the docs. But also, if it's possible to get docs for the latest release before LTS. 

closing: #146

**Comment by DanielSiepmann** [comment]
It is not the latest release. This one should always be the highest number.

Some extensions might have multiple latest releases, e.g. one for v10 and one for v9. E.g. system extensions or even 3rd Party extensions that have different versions for matching TYPO3 versions.

master always refers 1:1 to the git branch master. That's already documented at https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Migrate.html#supported-branches. Do you wanna have it documented somewhere else for other target groups?

We wanna discuss how to handle update of docs.typo3.org for LTS in future in core development anyway. Keeping master as it is, is one possible way to reach that goal.
