### ISSUE TITLE
Make documentation changes for new dashboard extension

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#136]
* [x] system extension documentation is not yet rendered, see subtree split of dashboard: https://github.com/TYPO3-CMS/dashboard

final URL should be: https://docs.typo3.org/c/typo3/cms-dashboard/master/en-us/

* [x] add to [system extension](https://docs.typo3.org/Home/SystemExtensions.html) page
* [x] add to [list of new documentation](https://docs.typo3.org/Home/WhatsNew.html#new-documentation)

Open question?

* should we add information about dashboard extension to "TYPO3 Explained" somewhere?

**Comment by DanielSiepmann** [comment]
The extension is now rendered and available. I've also added it to the system extension page.
