### ISSUE TITLE
Permanent short URLs for major doc topics

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#138]
What we already have:

* TypoScript reference: tsref.de 
* ... ?

Suggestion from Benni:

* Installation Guide (sth. like docs.typo3.org/installation)
* System Requirements (docs.typo3.org/system-requirements)
* Contribution Workflow (docs.typo3.org/core-contribution)

I would favor maybe even shorter ones.

**Comment by DanielSiepmann** [comment]
Those redirects can be added to the nginx configuration. That can be done by TYPO3 Inc. or anyone else, once the repo is publicly available.

tsref.de is not owned by TYPO3, as far as I know. And there is also tsref.org as "de" is not what you might expect.

**Comment by sypets** [comment]
closing.
