### ISSUE TITLE
Lint .rst files (e.g. with OskarStark/doctor-rst)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#140]
> As second step I would suggest is to include a linter AND renderer as CI builds in each repo.

https://twitter.com/helhum/status/1246061661699690496

> In case it's useful for your project, our friend 
@OskarStark
 developed a linter for RST docs. It works great for Symfony Docs finding common issues and problems. It's open source:

https://twitter.com/symfonydocs/status/1245641093598687232

https://github.com/OskarStark/doctor-rst

From Symfony Docs

**Comment by alexander-nitsche** [comment]
There will be a first documentation validator on intercept side with this PR: https://github.com/TYPO3GmbH/site-intercept/pull/73 . Extending it with this reST linter in a next step could be promising.

**Comment by sypets** [comment]
@alexander-nitsche Can you give an update what the current status is now?

**Comment by alexander-nitsche** [comment]
The basic documentation validator integration on intercept side was rejected, so the reST linter will have to be integrated in a different way.

**Comment by linawolf** [comment]
The new php based rst rendering will also make linting easier.
