### ISSUE TITLE
20 Top accessed pages in Wiki - check, possibly delete and create redirects

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#142]
As suggested in https://decisions.typo3.org/t/documentation-content-what-to-do-about-the-wiki-revisited/583/3

Top accessed 20 pages on https://wiki.typo3.org (without the exceptions) by Matomo. (The exception should be handled separarely)

Possible steps to take:

1. Request redirect and delete page
2. or: update
3. or: add notes, e.g. `{{outdated}}`, `{{delete}}`

----

This still needs a decision: For content that exists on docs.typo3.org, the Wiki page can be removed and a redirect created. But some pages on wiki.typo3.org handles older TYPO3 versions.

**Can we remove content from Wiki that handles pre-ELTS versions? Can we remove any content from Wiki? How to deal with this and who decides?**

----

Check off when sufficiently handled:

## Over 1000 unique pageviews:

* 1 https://wiki.typo3.org/Main_Page - skip, will not redirect main page
* [ ] 2 https://wiki.typo3.org/Default_Orderings_and_Query_Settings_in_Repository
* [ ] 3 https://wiki.typo3.org/FAQ/Reset_admin_password
* [ ] 4 https://wiki.typo3.org/TYPO3_templates_repository

---

* 5 https://wiki.typo3.org/Others ? 
> No page with this name

----

* [x] 6 https://wiki.typo3.org/Upgrade 
> This was already partly moved to "Installation & Upgrade Guide", added 2 PRs TYPO3-Documentation/TYPO3CMS-Guide-Installation#140 and TYPO3-Documentation/TYPO3CMS-Guide-Installation#141, Wiki page can be removed and redirected when these are merged

> delete tag was added

----

## Over 500 unique pageviews:

* [x] 7 https://wiki.typo3.org/Fluid 
> "outdated" tag was added and link to [Fluid start page in "TYPO3 Explained"](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Fluid/Index.html)

---

* [ ] 8 https://wiki.typo3.org/How_to_upload_big_files

---

* [x] 9 https://wiki.typo3.org/Extension_Development,_using_Flexforms

> This page is outdated, there is an alternative on [docs.typo3.org](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/FlexForms/Index.html). BUT, the alternative on docs.typo3.org does not yet cover everything. I have added some more information to the docs page, such as subtypes_excludelist ...: TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#829, TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#832, TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#833

> delete tag was added

---

* [x] 10 https://wiki.typo3.org/Composer

Notes were added for outdated sections, page was marked as outdated and links to docs.typo3.org added.

----

* [ ] 11 https://wiki.typo3.org/How_to_use_the_Fluid_Standalone_view_to_render_template_based_emails

----

* [ ] 12 https://wiki.typo3.org/Dependency_Injection

Some can be moved to Extbase documentation. Link to newer documentation should be added. 

----

* [ ] 13 https://wiki.typo3.org/Extension_Developers_Guide
* [ ] 14 https://wiki.typo3.org/Extbase_HowTos
* [ ] 15 https://wiki.typo3.org/Fluid_Inline_Notation
* [x] 16 https://wiki.typo3.org/Realurl/manual
* [ ] 17 https://wiki.typo3.org/De:Faq/Reset_BE_password (German page)

## Over 100 unique pageviews:

* [ ] 18 https://wiki.typo3.org/How_to_uninstall_extensions
> There is an alternative in [Installation Guide: Extension Installation](https://docs.typo3.org/m/typo3/guide-installation/9.5/en-us/ExtensionInstallation/Index.html), this should get backported to 8.7 and below. 

----

* [ ] 19 https://wiki.typo3.org/Performance_tuning
* [ ] 20 https://wiki.typo3.org/Deprecation_Log
* [ ] 21 https://wiki.typo3.org/Opcode_Cache 
* [ ] 22 https://wiki.typo3.org/QueryResult
* [x] 23 https://wiki.typo3.org/Felogin
* [ ] 24 https://wiki.typo3.org/Add_your_own_favicon

----

* [ ] 25 https://wiki.typo3.org/Fr:TYPO3_Tutorial_for_Editors 

> French version of Tutorial for Editors

----

*  26 https://wiki.typo3.org/Category:Core_Team 
> This is a category page: ignore

---

*  27 https://wiki.typo3.org/Special:Categories 
> This is a categories overview: ignore

---

* [ ] 28 https://wiki.typo3.org/TypoScript_Constants
* [ ] 29 https://wiki.typo3.org/TypoScript_language_additions,_override
* [ ] 30 https://wiki.typo3.org/UTF-8_support
* [ ] 31 https://wiki.typo3.org/Help:Contents
* [ ] 32 https://wiki.typo3.org/wiki/ - Others - ?
* [ ] 33 https://wiki.typo3.org/TYPO3-Docker
* [ ] 34 https://wiki.typo3.org/T3BOARD20EU
* [ ] 35 https://wiki.typo3.org/Multidomain
* [ ] 36 https://wiki.typo3.org/Editors_(reST)
* [ ] 37 https://wiki.typo3.org/Content_Slide
* [ ] 38 https://wiki.typo3.org/Extension_Development,_Debugging
* [ ] 39 https://wiki.typo3.org/GraphicsMagick
* [ ] 40 https://wiki.typo3.org/De:INCLUDE_TYPOSCRIPT
* [ ] 41 https://wiki.typo3.org/TYPO3_Installation_on_Ubuntu
* [ ] 42 https://wiki.typo3.org/Core_Team
* [ ] 43 https://wiki.typo3.org/De:TYPO3_Tutorial_for_Editors
* [ ] 44 https://wiki.typo3.org/Backup
* [ ] 45 https://wiki.typo3.org/Inline_Relational_Record_Editing_1:n
* [ ] 46 https://wiki.typo3.org/Enhanced_Lazy_Loading

**Comment by susannemoog** [comment]
We now migrated all pages that have been accessed more than a couple of times in the last year with https://github.com/TYPO3-Documentation/T3DocTeam/issues/154 - I'm going to close this on.
