### ISSUE TITLE
[BEST PRACTICES] Good practices for structuring content on pages

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#147]
How to structure content on pages. Currently, there are several possibilities and we use all of these to structure content of a chapter:

1a. **"One-page":** everything on one page (as often in the TCAref).
1b. **"One-page with toc"**: like 1 and additionally  a _table of content_ at the top for the content on the page
2. Have an Index.rst and the content in subpages
2a. have only a toctree on the startpage (of a chapter) (as often done in "TYPO3 Explained")
2b. like 2a, but additionally, some introduction text on the startpage

There are several pros and cons for all approaches. "One-page" may make it difficult to understand the structure. Having everything on subpages can be annoying, because you may have to click back and forth. Having pages with very little content can be annoying, especially when you are paging through the pages. 

I always found it difficult to make these decisions and often was not really happy with the results. I also used to hate these toctree-only pages at the beginning but the all-in-one pages can be pretty overwhelming so during the course of working with the docs, the toctree-only-pages look not so bad to me by now.

I think you do have to also decide some on a case by case-basis, but I think having a best practice and doing this consistently (as far as possible) would make it easier for people to find their way around the docs. 

Having to make these general decisions every time you add docs or make larger changes makes it more difficult to write "good documentation". I would have like to have some tips or best practices at the beginning.

**Comment by sypets** [comment]
Lolli has restructured a lot, especially in TSref and TCAref, using more of the all-on-one-page approach. You can see this, when you compare the versions 9 and above with lower versions. 

Examples:

* [Simple data types (TSref)](https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/DataTypes/Index.html)  is now all on one page (see [7.6](https://docs.typo3.org/m/typo3/reference-typoscript/7.6/en-us/DataTypes/Index.html) version with subpages)
* [security guide system administrators](https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/Security/GuidelinesAdministrators/Index.html) is now all on one page ([8.7 version](https://docs.typo3.org/m/typo3/guide-security/8.7/en-us/GuidelinesAdministrators/Index.html) has only-toctree-on-start-pages)



In "TYPO3 Explained" we often have a toctree-only page with subchapters like "Introduction", "Quickstart" etc. If the content is pretty extensive, I think this is a good way to go. The pages "[FlexForm](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/FlexForms/Index.html)" and ["Create your own content elements"](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/ContentElements/AddingYourOwnContentElements.html) may get to a point, where the all-on-one-page approach makes it difficult and moving to the toctree-only-startpages might be a better idea (but as I said above, there are pros and cons for both ways). 

The TCAref subtypes pages are IMHO a bit difficult to read, because all renderTypes are on one page (and the examples were added). In the older version this did not exist yet.

Example:

* [TCA check master](https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Check.html), see [7.6](https://docs.typo3.org/m/typo3/reference-tca/7.6/en-us/Reference/Columns/Check/Index.html)

**Comment by sypets** [comment]
There was a discussion on Slack about something similar:

https://typo3.slack.com/archives/C028JEPJL/p1589798104000600

> I was looking at the TypoScript "getText" data type and I noticed that in the revamped documentation, the list of keys is no longer available: https://docs.typo3.org/m/typo3/reference-typoscript/10.4/en-us/DataTypes/Index.html#gettext Is that right or is it elsewhere?

> Ah yes. Now I can see that the information is there. In this case I think it does not help that heading levels are IMO insufficiently differentiated. In the screenshot, I think "cObj" does not look like it's a sub-section of "getText".

> Maybe we should move those info to a different level. Only keep the introduction, and link to a detail page with all the sub information?
> I've the feeling that we just "put stuff" somewhere most of the time. We do not separate stuff enought

> I think too much pages could be also counter-productive, so do not make it a absolute rule. If we got the "On this page" navigation menu (3rd level) back, IMHO this kind of reference documentation will regain some readability.

So here mentioned is

* difficult to see heading level (rather a question for the theme?)
* put things on one page or subpages
* missing subchapters in menu (theme)

todo: check how this looks now with updated theme.

**Comment by alexander-nitsche** [comment]
Both documentation types single-file documentation and full documentation are defined in the new documentation standard page https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/FileStructure.html: It is preferred to use the full documentation, but for those who need a transition period, the single-file documentation is a proven fallback. Regarding your decisions about the page structure: the basic structure for the start page is 

1. general information (package name, extension key, authors, license, etc.)
2. abstract (summary of project in few lines)
3. TOC

which solves your TOC-only "problem" with fluent text on the project's purpose.

**Comment by sypets** [comment]
@alexander-nitsche I think this is a misunderstanding here. I was not talking about the one file for the **entire project** vs several files in Documentation here but about how to structure the content **in a chapter.** We often have different approaches, sometimes

1. one single file, as in [FlexForms](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/FlexForms/Index.html)
2. or one Index.rst with **only** the table of contents as in [Ajax](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Ajax/Index.html), often with a page Introduction as subpage as in [Services](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Services/Index.html)
3. or a start page Index.rst with some text and a (more hidden) table of contents as in [Caching](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/CachingFramework/Index.html). 
  * Here one disadvantag is that the subpages are quite hidden - also since the menu is very long and the page can be very long, scroll down and you don't see the submenu, or if a page is further down in the main menu, you also do not see the submenu

I noticed that different people have different ways to do this or prefer one or the other and also the preference changed to only the table of contents on Index.rst in the past and more often a one page solution nowadays. I think here more consistency would be good and it would be good to collect the best practices.

**But, I am ok with having closed this issue** - I think for the structural things or more complex and general decisions, issues are not a good approach. This is probably better if talked about or handled elsewhere in a call or sprint.
