### ISSUE TITLE
Problems with standalone readme

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#152]
Should be supported: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/DirectoryFilenames.html#start-file

You can use README.md | README.rst in root directory (not in **Documentation** folder)

* [x] build is not automatically triggered
* [ ] The title README is displayed on start page
* [ ] "The Project's Title" is displayed instead of extension name 

![image](https://user-images.githubusercontent.com/13206455/98463041-cf447000-21b8-11eb-8dc8-4bd65668bc41.png)

* having "The Projects Title" can be avoided by supplying a Documentation/Settings.cfg with the title
* It is possible to have the top level menu items directly in the menu by not adding a title on the start page

see https://github.com/sypets/migrate2composer with `Documentation/Settings.cfg` in master and not in other branches (rendered: https://docs.typo3.org/p/sypets/migrate2composer/master/en-us/)

**Comment by sypets** [comment]
> build is not automatically triggered
has been fixed.

**Comment by alexander-nitsche** [comment]
@sypets : can this be closed?

**Comment by sypets** [comment]
I think that is problably a maintainer decision. I think rendering a standalone README works good enough for me. It would be nice if it were not necessary to include a Settings.cfg. I am closing. If there is still things left to do which will be fixed - we could use specific issues.
