### ISSUE TITLE
Search extension by extension key: result for rte_ckeditor_fontawesome and rte_ckeditor_images displayed, but extension not rendered on docs.typo3.org

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#155]
## todos

currently, we assume there are these problems:

* [ ] List of extensions generated by Intercept in `https://docs.typo3.org/Home/extensions.js `contains rte_ckeditor_fontawesome and rte_ckeditor_image even though these extensions are not rendered on docs.typo3.org (also not in the list of deployed docs on Intercept: https://intercept.typo3.com/admin/docs/deployments). This should be checked
* [ ]  incorrect redirect: the redirect for rte_ckeditor is too greedy:

```
https://docs.typo3.org/typo3cms/extensions/rte_ckeditor_fontawesome/9.2.0
-> https://docs.typo3.org/c/typo3/cms-rte-ckeditor/main/en-us_fontawesome/9.2.0

```

---

## Description of problem

I am not sure, where to report this issue. Please move if more appropriate somewhere else.

Reproduce:

1. Search for rte_ckeditor on https://docs.typo3.org/Home/ExtensionManualsSearch.html#extensionsmanualsearch
2. Click on **rte_ckeditor_fontawesome** or select latest version (9.2) for this extension
3. results in 404

Same for **rte_ckeditor_image**.

----

![image](https://user-images.githubusercontent.com/13206455/171987158-84e05b25-3c61-43cb-98a5-643dda3ae700.png)

**Comment by sypets** [comment]
June 1, 2022 - updated and corrected

---- 

checked for **rte_ckeditor_fontawesome** (but same goes for rte_ckeditor_image):

This problem still exists. 

This is what happens:

1. An URL is created based on the old scheme (before relaunch of rendering): https://docs.typo3.org/typo3cms/extensions/rte_ckeditor_fontawesome/9.2.0
2. This URL is (incorrectly) redirected:

`https://docs.typo3.org/typo3cms/extensions/rte_ckeditor_fontawesome/9.2.0`
-> ` https://docs.typo3.org/c/typo3/cms-rte-ckeditor/main/en-us_fontawesome/9.2.0
`


Notice the `/main/en-us_fontawesome`, also the /c/ is not correct and the vendor. This is a third party extension.
It looks like the redirect is too greedy for  `typo3/cms-rte-ckeditor`

Also, rte_ckeditor_fontawesome is not rendered on docs.typo3.org. There is no Documentation folder, so this extension should not be displayed in the search in the first place.

If it were rendered, the URL should be: 

https://docs.typo3.org/p/dirkpersky/rte-ckeditor-fontawesome/main/en-us/

See also extension repository: https://extensions.typo3.org/extension/rte_ckeditor_fontawesome

**Comment by brotkrueml** [comment]
The extension documentation search via docs.typo3.org is considered legacy:
https://docs.typo3.org/Home/ExtensionManuals.html#extension-manuals
The recommended way is to go to the TER, look for the extension, and then click on the "Documentation" link.
Closing for now.
