### ISSUE TITLE
Matomo: Backend fails for custom statistics

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/T3DocTeam#157]
Sybille Peters Apr 6th at 9:42 AM

Hi, about Matomo: There are some problems - I don't know if there are workarounds for this:

Selecting a larger timeframe (e.g. 1.1.2021 - 06.04.2021) results in error - due to this it is not possible to select a larger timeframe than say a month. (This never worked for me and I already contacted the admin about it)
   > Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Matomo administrator for assistance.

**Comment by alexander-nitsche** [comment]
hi sybille, the matomo machine memory has been upgraded and first tests by thomas janke show that this has improved the user experience a lot when requesting custom statistics in the backend .. would you test if your runtime problems have been solved now?

**Comment by sypets** [comment]
behaviour has improved. @alexander-nitsche  Please close.
