### ISSUE TITLE
Matomo: Creating a new segment fails

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/T3DocTeam#158]
Sybille Peters Apr 6th at 9:42 AM

Hi, about Matomo: There are some problems - I don't know if there are workarounds for this:

I just tried to create a new segment. I wanted to get an overview of visitors coming from skillsdisplay.eu using this tutorial: https://matomo.org/faq/how-to/how-do-i-get-the-most-popular-landing-pages-viewed-b[…]specific-channel-type-direct-search-website-social-or-campaign/

Clicking on "all visits" > "Add new segment" > "Referrers"  > "Referrer url" i get the error message:

> Please contact support to make these changes on your behalf. To modify a pre-processed segment, a user must have admin access or super user access
   
I am not modifying an existing, I am trying to create a new segment. And this used to work (I already created segments)

**Comment by alexander-nitsche** [comment]
hi sybille, thomas janke is on it: he will first update matomo and then come back and have a look at your findings.

**Comment by alexander-nitsche** [comment]
hi sybille, thomas has updated the piwik.typo3.org matomo instance and checked the general status quo: would you recheck your issues next and report if they still exist?

**Comment by sypets** [comment]
This now works. closing.
