### ISSUE TITLE
Define how to discuss topics and create decisions

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/T3DocTeam#16]
# Problem

For the TYPO3 Core Team there is https://decisions.typo3.org/. But we also have some huge topics we need to tackle. Most of them involve different opinions and ideas for solutions. We need to discuss them and find a solution we can agree on.

# Possible solutions

## Use Github Issues

We can use Github issues and down or upvote the first comment. But this is limited. There is only yes or no.

## Use decisions.typo3.org

We can add a new category at https://decisions.typo3.org/categories. This will add a larger audience and we are re-using existing workflows within the community. Still we have to discuss whether the Core Team likes this idea.

## Use talk.typo3.org

* Is to be **the** platform for discussion
* We can get our category
* Voting?

# Additional information:

* information about current status of **talk.typo3.org**: https://talk.typo3.org/t/welcome-to-talk-typo3-org/8
* **decisions.typo3.org** : this forum is exclusively used by the core team. Only the core team can open discussions there

**Comment by nito-web** [comment]
Very nice and transparent idea

**Comment by DanielSiepmann** [comment]
For now I'll try to gather more information about decisions.typo3.org and comment once I've collected them.

The main goal for me:
- [x] Ask whether it's ok to share this platform with the Documentation Team.
- [x] Get how the categories work.

**Comment by DanielSiepmann** [comment]
There is also https://talk.typo3.org/, which I didn't know. So we would likely open a new category there instead.

Categories provide the following features:
- Grouping of related topics / threads.
- Right management
- Templates for new posts.

If we decide to use this, the server team might create the category and grant according access rights to us, inside talk.typo3.org.

**Comment by sypets** [comment]
FYI, because this topic also concerns other teams, I started an issue for t3o: https://git-t3o.typo3.org/t3o/typo3.org/issues/320

**Comment by sbusemann** [comment]
Hi Daniel and all, I think to solve that issue, we should try to set up a combined team sprint with at least t3o, server and documentation team. We should also invite the core team (leaders) that we find a solution which fits for all.

**Comment by sypets** [comment]
@sbusemann thank you. 

@DanielSiepmann The current answer is that decisions.typo3.org is used exclusively by the core team. Only the core team has access to open up topics there.

**Comment by DanielSiepmann** [comment]
I've updated my comment above. Opening a category for us would be possible at talk.typo3.org.

But @sbusemann is right. We can join forces and check out there existing workflows an benefit from their experiences.

**Comment by sypets** [comment]
I would like to add to the list of possible solutions:

* Slack call (e.g. focused Slack call on one topic)
* Sprint

I guess, it very much depends on the type of topic, what is most suited for the job.

**Comment by sypets** [comment]
About talk: I got this information from Andri Steiner from the server team:

_" Hi Sybille. Please give us some time while we prepare the migration of all mailinglist/newsgroups to this new forum. There are some things we have to prepare beforehand (for example, we might need a new solution for the TYPO3-announce mailinglist), as soon as all answer to such questions are clear, we're ready to move forward quite fast.
You can also follow the current process at https://talk.typo3.org/t/welcome-to-talk-typo3-org/8"_

I will add this link and additional information to the top comment in this thread.

**Comment by sypets** [comment]
@DanielSiepmann I made some changes to the first posting. Hope it's ok:

* crossed out decisions because that is now definitely off the table
* added talk.typo3.org

**Comment by sypets** [comment]
After seeing [more open decisions](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3ATYPO3-Documentation+label%3A%22decision+required%22) piling up for months I have changed my opinion on this:

* I think decisions.typo3.org is currently the best option for coming to a decision. It is a **dedicated decisions platform**. If the decision is important and we need input from the community, a "decision" could also additionally be featured in a news on https://typo3.org or on twitter.
* Discussing (big) decisions on Slack is not an option. Slack is not the best platform for a focused discussion of a more complex topic. It can be used for small things. 
* Participation and visibility on GitHub is (currently) very low.
* talk.typo3.org is (currently) not an option. It is not available yet. Also, why use talk if we have a **dedicated decsions platform for decisions which is called decisions.typo3.org**?
* some things can be discussed during Slack call, but for some things it is important to hear some more pros and cons from various people. 

In any case: It would be important to come to decisions on some things and to create common best practices. To make sure, the people creating documentation work for a common goal and not on different (or even contradicting) strategies.

**Comment by sypets** [comment]
**Update:**

As talk.typo3.org is still not available, I now requested a **documentation** category on decisions.typo3.org from core team. To be updated ...

**Comment by sypets** [comment]
We now have a documentation category on https://decisions.typo3.org. Closing here ...
