### ISSUE TITLE
TYPO3: Replace `git@github.com:typo3/typo3` with `git://github.com/typo3/typo3`

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/T3DocTeam#162]
Currently there are three ways to reference the TYPO3 github repository:

- https://github.com/typo3/typo3
- git://github.com/typo3/typo3
- git@github.com:typo3/typo3

and should be reduced to only two:

- https://github.com/typo3/typo3
- git://github.com/typo3/typo3

where the first should be used for all browsing links, e.g. linking to a specific file in the repository, and the latter should be used whenever the user is working with the git repository, e.g. for `git clone`.

**Comment by simonschaufi** [comment]
Everywhere I look i always see git@xxx urls, like on stackoverflow and so on. Why is git://xxx.com the "better" way? Even when you want to clone a github repo and switch to ssh, the url looks like this: `git@github.com:TYPO3-Documentation/T3DocTeam.git` so I don't see the point why everyone should switch to a format that nobody uses. A big veto against it. :-1:

**Comment by mbrodala** [comment]
@simonschaufi See https://github.com/TYPO3-Documentation/T3DocTeam/issues/163 which replaces this one.

The original idea was that you could understand right away that `git://github.com/typo3/typo3` is a Git clone URL whereas `git@github.com:typo3/typo3` is not as clear. Also one could easily convert `https://github.com/typo3/typo3` to `git://github.com/typo3/typo3` by simply switching the scheme.

But as mentioned in the other issue there are problems with private Git repositories so we won't be following this approach anyways.

I'll close this one.
