### ISSUE TITLE
TYPO3: Replace all `typo3.org/api` links

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/T3DocTeam#171]
The TYPO3 API seems to have been available in ancient times at http[s]://typo3.org/api which returns currently a 404.

There are still some links to typo3.org/api in the TYPO3 documentation. Replace them with an up-to-date URL or remove them.

Current results for 
```bash
t3docs-tools (feature-search-repos)$ ./bashScripts/get-repos.sh
t3docs-tools (feature-search-repos)$ ./bashScripts/search-repos.sh "grep -rnIE 'typo3.org\/api' --exclude-dir='.git' ."
```
are
```
------------------------------------------------------------------------
sphinx_typo3_theme_rendering_test (master): 1 search results.
------------------------------------------------------------------------
./Documentation/Settings.cfg:64:# t3api         = https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
T3DocTeam (master): 1 search results.
------------------------------------------------------------------------
./Documentation/Settings.cfg:63:# t3api         = https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
t3SphinxThemeRtdDemoDocs (master): 1 search results.
------------------------------------------------------------------------
./Documentation/Settings.cfg:64:# t3api         = https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Book-ExtbaseFluid (10.4): 1 search results.
------------------------------------------------------------------------
./Documentation/Settings.cfg:55:t3api      = http://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Example-ExtensionManual (master): 2 search results.
------------------------------------------------------------------------
./Localization.de_DE.tmpl/Settings.cfg:63:# t3api         = https://typo3.org/api/typo3cms/
./Localization.fr_FR.tmpl/Settings.cfg:63:# t3api         = https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Reference-TCA (7.6): 4 search results.
------------------------------------------------------------------------
./Documentation/Settings.yml:10:    - http://typo3.org/api/typo3cms/
./Documentation/Settings.cfg:61:; t3api has no inventory: https://typo3.org/api/typo3cms/objects.inv
./Documentation/Settings.cfg:62:; t3api      = https://typo3.org/api/typo3cms
./Settings.cfg:57:t3cmsapi      = https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Reference-Typoscript (master): 2 search results.
------------------------------------------------------------------------
./Documentation/Functions/Imagelinkwrap.rst:341:__ http://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
./Documentation/Functions/Imagelinkwrap.rst:342:__ http://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Reference-Typoscript (11.5): 2 search results.
------------------------------------------------------------------------
./Documentation/Functions/Imagelinkwrap.rst:341:__ https://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
./Documentation/Functions/Imagelinkwrap.rst:342:__ https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Reference-Typoscript (10.4): 2 search results.
------------------------------------------------------------------------
./Documentation/Functions/Imagelinkwrap.rst:331:__ https://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
./Documentation/Functions/Imagelinkwrap.rst:332:__ https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Reference-Typoscript (9.5): 2 search results.
------------------------------------------------------------------------
./Documentation/Functions/Imagelinkwrap.rst:339:__ https://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
./Documentation/Functions/Imagelinkwrap.rst:340:__ https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Reference-Typoscript (8.7): 2 search results.
------------------------------------------------------------------------
./Documentation/Functions/Imagelinkwrap/Index.rst:371:__ http://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
./Documentation/Functions/Imagelinkwrap/Index.rst:372:__ http://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Reference-Typoscript (7.6): 2 search results.
------------------------------------------------------------------------
./Documentation/Functions/Imagelinkwrap/Index.rst:376:__ http://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
./Documentation/Functions/Imagelinkwrap/Index.rst:377:__ http://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
typo3-docs-typo3-org-resources (master): 8 search results.
------------------------------------------------------------------------
./Documentation/Settings.yml:28:    - http://typo3.org/api/typo3cms/
./userroot/scripts/bin/decode_sphinx_inventory.py:122:    '://typo3.org/api/typo3cms'             : 't3api', # current stable
./userroot/scripts/bin/decode_sphinx_inventory.py:132:    '://typo3.org/api/flow'        : 'api',
./userroot/scripts/bin/conf-2015-10.Reference.Settings.cfg:107:t3api      = http://typo3.org/api/typo3cms/
./userroot/scripts/bin/conf-2015-10.Reference.Settings.cfg:112:# t3api         = https://typo3.org/api/typo3cms/
./TemplatesForCopying/ExampleFiles/Settings-extensive.cfg:55:# t3api         = https://typo3.org/api/typo3cms/
./TemplatesForCopying/ExampleFiles/Defaults.cfg:3:# t3api         = https://typo3.org/api/typo3cms/
./TemplatesForCopying/a-starter-for-a-project-with-documentation/Documentation/_make/Defaults.cfg:51:# t3api         = https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
Vagrant-Ansible-T3Documentation-Server (master): 2 search results.
------------------------------------------------------------------------
./Documentation/_make/Defaults.cfg:51:# t3api         = https://typo3.org/api/typo3cms/
./Documentation/Settings.cfg:51:# t3api         = https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
```

**Comment by linawolf** [comment]
current situation:


------------------------------------------------------------------------
T3DocTeam (main): 1 search results.
------------------------------------------------------------------------
- [x] Documentation/Settings.cfg:63:# t3api         = https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Reference-TCA (7.6): 4 search results.
------------------------------------------------------------------------
- [x] Documentation/Settings.cfg:61:; t3api has no inventory: https://typo3.org/api/typo3cms/objects.inv
- [x] Documentation/Settings.cfg:62:; t3api      = https://typo3.org/api/typo3cms
- [x] Documentation/Settings.yml:10:    - http://typo3.org/api/typo3cms/
- [x] Settings.cfg:57:t3cmsapi      = https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Reference-Typoscript (main): 2 search results.
------------------------------------------------------------------------
- [x] Documentation/Functions/Imagelinkwrap.rst:341:__ https://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
- [x] Documentation/Functions/Imagelinkwrap.rst:342:__ https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Reference-Typoscript (11.5): 2 search results.
------------------------------------------------------------------------
- [x] Documentation/Functions/Imagelinkwrap.rst:341:__ https://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
- [x] Documentation/Functions/Imagelinkwrap.rst:342:__ https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Reference-Typoscript (10.4): 2 search results.
------------------------------------------------------------------------
- [x] Documentation/Functions/Imagelinkwrap.rst:331:__ https://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
- [x] Documentation/Functions/Imagelinkwrap.rst:332:__ https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Reference-Typoscript (9.5): 2 search results.
------------------------------------------------------------------------
- [x] Documentation/Functions/Imagelinkwrap.rst:339:__ https://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
- [x] Documentation/Functions/Imagelinkwrap.rst:340:__ https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Reference-Typoscript (8.7): 2 search results.
------------------------------------------------------------------------
- [x] Documentation/Functions/Imagelinkwrap/Index.rst:371:__ https://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
- [x] Documentation/Functions/Imagelinkwrap/Index.rst:372:__ https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
TYPO3CMS-Reference-Typoscript (7.6): 2 search results.
------------------------------------------------------------------------
- [x] Documentation/Functions/Imagelinkwrap/Index.rst:376:__ https://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
- [x] Documentation/Functions/Imagelinkwrap/Index.rst:377:__ https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
Vagrant-Ansible-T3Documentation-Server (master): 2 search results.
------------------------------------------------------------------------
- [x] Documentation/Settings.cfg:51:# t3api         = https://typo3.org/api/typo3cms/
- [x] Documentation/_make/Defaults.cfg:51:# t3api         = https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
t3SphinxThemeRtdDemoDocs (master): 1 search results.
------------------------------------------------------------------------
- [x] Documentation/Settings.cfg:64:# t3api         = https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
------------------------------------------------------------------------
typo3-docs-typo3-org-resources (master): 8 search results.
------------------------------------------------------------------------
- [x] TemplatesForCopying/a-starter-for-a-project-with-documentation/Documentation/_make/Defaults.cfg:51:# t3api         = https://typo3.org/api/typo3cms/
- [x] TemplatesForCopying/ExampleFiles/Settings-extensive.cfg:55:# t3api         = https://typo3.org/api/typo3cms/
- [x] TemplatesForCopying/ExampleFiles/Defaults.cfg:3:# t3api         = https://typo3.org/api/typo3cms/
- [x] Documentation/Settings.yml:28:    - http://typo3.org/api/typo3cms/
- [x] userroot/scripts/bin/decode_sphinx_inventory.py:122:    '://typo3.org/api/typo3cms'             : 't3api', # current stable
- [x] userroot/scripts/bin/decode_sphinx_inventory.py:132:    '://typo3.org/api/flow'        : 'api',
- [x] userroot/scripts/bin/conf-2015-10.Reference.Settings.cfg:107:t3api      = http://typo3.org/api/typo3cms/
- [x] userroot/scripts/bin/conf-2015-10.Reference.Settings.cfg:112:# t3api         = https://typo3.org/api/typo3cms/

**Comment by linawolf** [comment]
The following are still open:

------------------------------------------------------------------------
typo3-documentation/TYPO3CMS-Example-ExtensionManual/main: 2 search result(s)
------------------------------------------------------------------------
- [x] Localization.fr_FR.tmpl/Settings.cfg:63:# t3api         = https://typo3.org/api/typo3cms/
- [x] Localization.de_DE.tmpl/Settings.cfg:63:# t3api         = https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
typo3-documentation/TYPO3CMS-Reference-TCA/7.6: 1 search result(s)
------------------------------------------------------------------------
- [x] Documentation/Settings.yml:10:    - http://typo3.org/api/typo3cms/
------------------------------------------------------------------------
typo3-documentation/TYPO3CMS-Reference-Typoscript/10.4: 2 search result(s)
------------------------------------------------------------------------
- [x] Documentation/Functions/Imagelinkwrap.rst:331:__ https://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
- [x] Documentation/Functions/Imagelinkwrap.rst:332:__ https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
typo3-documentation/TYPO3CMS-Reference-Typoscript/11.5: 2 search result(s)
------------------------------------------------------------------------
- [x] Documentation/Functions/Imagelinkwrap.rst:341:__ https://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
- [x] Documentation/Functions/Imagelinkwrap.rst:342:__ https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
typo3-documentation/TYPO3CMS-Reference-Typoscript/7.6: 2 search result(s)
------------------------------------------------------------------------
- [x] Documentation/Functions/Imagelinkwrap/Index.rst:376:__ https://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
- [x] Documentation/Functions/Imagelinkwrap/Index.rst:377:__ https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
typo3-documentation/TYPO3CMS-Reference-Typoscript/8.7: 2 search result(s)
------------------------------------------------------------------------
- [x] Documentation/Functions/Imagelinkwrap/Index.rst:371:__ https://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
- [x] Documentation/Functions/Imagelinkwrap/Index.rst:372:__ https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
typo3-documentation/TYPO3CMS-Reference-Typoscript/9.5: 2 search result(s)
------------------------------------------------------------------------
- [x] Documentation/Functions/Imagelinkwrap.rst:339:__ https://typo3.org/api/typo3cms/search/all_69.html?imageLinkWrap
- [x] Documentation/Functions/Imagelinkwrap.rst:340:__ https://typo3.org/api/typo3cms/
------------------------------------------------------------------------
typo3-documentation/typo3-docs-typo3-org-resources/master: 1 search result(s)
------------------------------------------------------------------------
- [ ] userroot/scripts/bin/decode_sphinx_inventory.py:131:    '://typo3.org/api/flow'        : 'api',
------------------------------------------------------------------------
Total: 14 search result(s)
------------------------------------------------------------------------

**Comment by alexander-nitsche** [comment]
All tasks done.
