### ISSUE TITLE
TYPO3: Maintain contribution files organization-wide

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#172]
We added a CONTRIBTING.md to every repo a while ago. This is not really necessary, because you can set default files for an organization, such as CONTRIBUTING.md and SUPPORT.md or also CODE_OF_CONDUCT.md (which could link to TYPO3 code of conduct). Also, it might be possible to use issue and PR templates eventually, but make them available per organization, not repo. 

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types

@alexander-nitsche  Since you are already unifying / cleaning up. Can you look into it?

**Comment by alexander-nitsche** [comment]
hi sybille, what about writing here your detailed concept with fetching what from there and placing in which file, and have a discussion about it. The doing should be the smaller part here.

**Comment by linawolf** [comment]
We might work on this in the future but it does not really hurt the way it is for now
