### ISSUE TITLE
TYPO3: Forge definitive How-To-Document Guide

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/T3DocTeam#175]
There is already a guide for documentation, and there are new posts from Open Strategy Partners and the Extension Award team about the right way to document. Bring all sources together in a final guide.

How-To-Document Guide (TYPO3 Documentation Team): https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/Index.html
Writer's Guide (Open Strategy Partners): https://github.com/TYPO3-Documentation/typo3-writing-guide
Good Documentation Criteria 1 (Extension Award Team): https://github.com/sypets/typo3-extension-documentation-award/issues/11#issuecomment-987687528
Good Documentation Criteria 2 (Extension Award Team): https://github.com/sypets/typo3-extension-documentation-award/issues/14

**Comment by linawolf** [comment]
Closing this as we will archive the repo. No one has felt the need to work on this for 2 years
