### ISSUE TITLE
TYPO3: Documentation search with no results

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/T3DocTeam#177]
The monthly Matomo report in the _documentation-team_ Slack channel lists all searches in the TYPO3 documentation with no results. These search words should be checked and be described properly in the documentation, if relevant.

These are the search words which should be checked:

### February 2022

- [ ]  _processDatamapClass_
  Alex: is valid array key in TYPO3 v9-v12, and is already described in typo3-documentation/TYPO3CMS-Reference-CoreApi/main:Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst:
      ```
      $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_tcemain.php']['processDatamapClass'][] = ..
      ```
- [ ] _contentPostProc-all_
  Alex: is valid array key in TYPO3 v7-v12, and is already described in typo3-documentation/TYPO3CMS-Reference-CoreApi/main:Documentation/ApiOverview/Hooks/Hooks/Index.rst:
      ```
      if (is_array($this->TYPO3_CONF_VARS['SC_OPTIONS']['tslib/class.tslib_fe.php']['contentPostProc-all'])) {
          ..
      }
      ```
- [ ] _Swift_Attachment_
  Alex: is valid class in TYPO3 v7-v9, and is already described in typo3-documentation/TYPO3CMS-Reference-CoreApi/9.5:Documentation/ApiOverview/Mail/Index.rst:
      ```
      $mail->attach(\Swift_Attachment::fromPath('my-document.pdf'));
      ```

### January 2022

- getConcreteQueryBuilder (ignored)
  Alex: is a valid method in TYPO3 v8-v12, but not sure that it should be described explicitly in the documentation.

### November 2021

- [ ]  _frame_class_
  Alex: introduced with TYPO3 v8, used in fluid_styled_content, listed in changelog of TYPO3 v8, still in TYPO3 Core (v11)
- [ ]  _doNotShowLabel_
  Alex: EXT:form variable of current TYPO3 Core (v11)
- [x]  _PackageArtifact_
  Alex: EXT:core creates package artifacts for Composer-based installations since TYPO3 v11, it is mentioned in the changelog of feature #94996, but it talks about “a persistent artifact” instead of using the exact name “PackageArtifact.php” which could be a valid search term of a developer.

### October 2021

- [ ]  _AbstractWidgetController_
  Alex: historical Fluid class
- [ ]  _autoCreateRedirects_
  Alex: EXT:redirects configuration settings.redirect.autoCreateRedirects
- [x]  _generatepackagestates_
  Alex: typo3-console CLI command typo3cms install:generatepackagestates

### September 2021

- [x]  _AdditionalConfiguration_
- [ ]  _config.tx_extbase_

**Comment by linawolf** [comment]
PackageArtifact -> https://forge.typo3.org/issues/96711

**Comment by mbrodala** [comment]
I don't think `getConcreteQueryBuilder()` needs an explicit mention. It's not meant as public API (tagged as `@internal`) and is only provided in case the wrapping TYPO3 `QueryBuilder` does not suffice.

**Comment by linawolf** [comment]
see https://review.typo3.org/c/Packages/TYPO3.CMS/+/73337

**Comment by alexander-nitsche** [comment]
Added findings of February 2022:  processDatamapClass, contentPostProc-all and Swift_Attachment.

**Comment by linawolf** [comment]
We will keep improving the search after the switch to the PHP based rst rendering
