### ISSUE TITLE
Rights and access management in Github

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#18]
For some repos there are teams (e.g. "Team Contribution Workflow"), for other repos, individual contributors are set as "collaborators". 

# Suggestion

* [ ] Decide how this is best efficiently handled
* [ ] Add the people who are capable and willing to contribute in a positive way to existing manuals

# Benefit

* There are more people who can be added as reviewers and who can merge patches

# Clarification

It might be good to clarify the rights management, e.g.

**Comment by sypets** [comment]
I think for question 1 it might be a combination of:

* [**Owner** of team workspace](https://github.com/orgs/TYPO3-Documentation/people) 
* [team of repository](https://github.com/orgs/TYPO3-Documentation/teams) 
* [collaborators of repository](https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-FrontendLocalization/settings/collaboration)

That works for the Frontend Localization Guide, see: https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-FrontendLocalization/

**Comment by DanielSiepmann** [comment]
@marble already restructured the organization and access rights.
