### ISSUE TITLE
Extension Manual Search does not find some extension docs which are rendered on docs.typo3.org

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#192]
Reproduce

1. got to https://docs.typo3.org/Home/ExtensionManuals.html
2. Search for rte_ckeditor
3. Perform the same search on extension.typo3.org: https://extensions.typo3.org/?L=0&id=1&tx_solr%5Bq%5D=rte_ckeditor
4. Compare the results

* the extension rte_ckeditor_codesnippet has documentation on docs.typo3.org: https://docs.typo3.org/p/ehaerer/rte-ckeditor-codesnippet/main/en-us/ but is not displayed in the result

![image](https://user-images.githubusercontent.com/13206455/171987335-6c60a22e-baec-49e8-ac6c-adee8d57fa55.png)

---

Related:

* #155  (this is similar but the other way around: extensions are displayed which should not be)

**Comment by brotkrueml** [comment]
"rte_ckeditor" is a system extension and therefore not available on TER. Additionally, the extension documentation search via docs.typo3.org is considered legacy:
https://docs.typo3.org/Home/ExtensionManuals.html#extension-manuals
The recommended way is to go to the TER, look for the extension, and then click on the "Documentation" link.
Closing for now.
