### ISSUE TITLE
Reintroduce "start" anchors for start pages

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/T3DocTeam#198]
This enables us to link to all start pages with 

```
:ref:`mytutorial:start` again
```

**Comment by linawolf** [comment]
Applied to all manuals and documented in How to document

**Comment by linawolf** [comment]
@sypets offered to replace all existing links like 
```
:doc:`[a-zA-Z0-9]+:Index`
```
with :ref: links to start again

**Comment by sypets** [comment]
We have 2 cases (with and without anchor):

1.
```
:doc:`t3tsref:Index`
```

use regex: 
```
:doc:`[a-zA-Z0-9]+:Index`
```
2. with anchor

```
:doc:`TCA Reference <t3tca:Index>`

```

use regex:
```
:doc:`([a-zA-Z0-9 ]+) <[a-zA-Z0-9]+:Index>`
```


In directory above all TYPO3CMS repos:

list of repos (without anchor):

```
grep -l -r -P ':doc:`[a-zA-Z0-9]+:Index`' */Documentation | cut -f1 -d'/' | sort -u
```

change (without anchor)

```
grep -l -r -P ':doc:`[a-zA-Z0-9]+:Index`' */Documentation | while read i;do echo "$i";perl -pi -e 's/:doc:`([a-zA-Z0-9]+):Index`/:ref:`$1:start`/g' "$i";done
```

change with anchor:

```
grep -l -r -P ':doc:`[A-Za-z0-9 ]+ <[A-Za-z0-9]+:Index>`' */Documentation |  while read i;do echo "$i";perl -pi -e 's/:doc:`([A-Za-z0-9 ]+) <([A-Za-z0-9]+):Index>`/:ref:`$1 <$2:start>`/g' "$i";done
```

**Comment by sypets** [comment]
These were the manuals I had locally where I had hits, should be done now:

- DocsTypo3Org-Homepage-sypets
- TYPO3CMS-Example-ExtensionManual-sypets
- TYPO3CMS-Guide-ContributionWorkflow-sypets
- TYPO3CMS-Guide-HowToDocument-sypets
- TYPO3CMS-Reference-CoreApi-sypets
- TYPO3CMS-Reference-TSconfig-sypets
- TYPO3CMS-Reference-Typoscript-sypets
