### ISSUE TITLE
TYPO3 7.6 is no longer in ELTS since 2022-11-30 but the ELTS notice is displayed

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#199]
This is based on information on get.typo3.org: 

> This version is not supported anymore.
The TYPO3 CMS community supported from 2015-11-10 until 2018-11-27. Extended security & compatibility support (ELTS) expired on 2022-11-30.

https://get.typo3.org/version/7

> Please consider updating to a newer version.

---------

On the 7.6 docs page: 

> TYPO3 v7 has reached its end-of-life November 30th, 2018 and is not maintained by the community anymore.
> You can order Extended Long Term Support (ELTS) here: [TYPO3 ELTS](https://typo3.com/services/extended-support-elts).

https://docs.typo3.org/m/typo3/reference-coreapi/7.6/en-us/ApiOverview/

-------

Message could be changed to similar message as displayed for 6.2: 
https://docs.typo3.org/m/typo3/reference-coreapi/6.2/en-us/ApiOverview/

> TYPO3 **v6** has reached its end-of-life **April 18th, 2017** and is not maintained by the community anymore. Looking for a stable version? Use the version switch on the top left.
> There is no further ELTS support. It is strongly recommended updating your project.

----

Also, you can't find any link or information about the 7 version on get.typo3.org anymore, you have to manually e.g. replace the 8 with a 7 the URL, https://get.typo3.org/version/7

----

ELTS:

| version | until        | status |
| ----------- | ------------ | --------- |
| 7.6         | 2022-11-30 | expired |
| 8.7         |   2024-03-31 | available |

**Comment by DavidBruchmann** [comment]
quite interesting, that the links can be adjusted, knew it for the downloads only.
https://get.typo3.org/version/3.5

**Comment by linawolf** [comment]
Seems like this is solved
