### ISSUE TITLE
Upgrade Guide: missing information on DB array

### ISSUE THREAD

**Issue by clivebeckett** [TYPO3-Documentation/T3DocTeam#20]
Dear DocTeam,

I finally took the step to upgrade my T3 installation from 7LTS to 8LTS. For that I followed the [Upgrade Guide](https://docs.typo3.org/typo3cms/InstallationGuide/Upgrade/Index.html) provided in the Docs.

The 1st thing I noticed: under **Install the New Source** it says I could use the Core Updater – which for me only works for minor updates, not for upgrades. If that is the normal behaviour, it should be mentioned in the _Upgrade_ Guide that this only applies to _updates._

And the 2nd, more important thing: after installing the new source and re-linking typo3_src I couldn’t move on with the next step because all that was shown when calling the backend was an error message. After a while of searching I found the reason and I suggest to mention this in the Upgrade Guide on the **Install the New Source** page: the structure of and also some of the keys in the **DB array in LocalConfiguration.php** had to be changed.

Thanks!

Cheers,
Clive.

**Comment by DanielSiepmann** [comment]
Thanks for reporting @clivebeckett.
I'll mention the necessary Steps about the `LocalConfiguration.php` for 7 -> 8 Updates.

@mbrodala can you tell me whether the "Core Updater" only works with minor updates? So I'll update that in the docs accordingly.

**Comment by sypets** [comment]
This issue should be in : https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/issues

Since it's not possible to move issues in Github (AFAIK), I would suggest closing this one and opening a new one that refernces this. 

Done: https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/issues/24
