### ISSUE TITLE
"Inside TYPO3" 8.7 is stilled rendered but not with banner for older versions

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#200]
https://docs.typo3.org/m/typo3/reference-inside/8.7/en-us/CoreArchitecture/ContextSensitiveHelp/ImplementingCsh/Index.html

The same is probably true for the other older references which were migrated, such as "FAL", "Skinning" etc.

-----

In TYPO3 Explained there is a banner for older versions:

https://docs.typo3.org/m/typo3/reference-coreapi/8.7/en-us/

![image](https://github.com/TYPO3-Documentation/T3DocTeam/assets/13206455/11e59782-fa87-495d-a524-abdf4415477a)

**Comment by brotkrueml** [comment]
Also version 7.6:
https://docs.typo3.org/m/typo3/reference-inside/7.6/en-us/CoreArchitecture/ContextSensitiveHelp/ImplementingCsh/Index.html

**Comment by linawolf** [comment]
We would have to unarchive them to change them. Should we do that?

**Comment by brotkrueml** [comment]
Yup, unarchive, change, archive again.

**Comment by brotkrueml** [comment]
Done
