### ISSUE TITLE
Find a good way to structure the documentation issues on github

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#21]
# Current status

* Every manual has a repo on github
* For every repo, issues can be created
* For _this repo_  (t3DocTeam), issues for general topics are created. 
* Some more general things can also be found in the [theme repo](https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/issues) and the [startpage](https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/issues) (Home / Welcome) repo 

# Helpful links

* [Open Issues in TYPO3 Documentation](https://github.com/search?o=desc&q=org%3ATYPO3-Documentation+type%3Aissue&s=updated&state=open&type=Issues)
* Example for using project boards : https://github.com/TYPO3-Documentation/T3DocTeam/projects/5

# Open questions

As this repo is now used for general things that are actually a _to-be-decided_ thing or something better that requires a concept, managing the issues in this repo is especially challenging. 

* [x] Is there a way to define subissues on Github? This is probably most useful for this T3DocTeam repo: **no**
* [x] Which labels do we want? Should we have the same labels for all repos?
**The labels are defined and assigned by the assignee.**
* [ ] Do we use milestones and how do we use them (e.g. to organize a sprint?)
* [ ] What is the best way to use the Projects? Should we use one project for one repo or several (as is now the case here)? Currently, the Projects are used in this repo T3DocTeam to categorize the issues. 

 
# Possible ideas and solutions

* [ ] **Issue templates** can be created (if applicable). You can create several templates for bug, feature request etc.
* [ ] Use **milestones** to group issues into one "sprint" with a desired due date (like the core does)

**Comment by DanielSiepmann** [comment]
>  Is there a way to define subissues on Github? This is probably most useful for this T3DocTeam repo

Not as far as I know, perhaps someone else knows this.

>  which labels do we want? Should we have the same labels for all repos?

I do not have any opinion about that yet. As I'm not used to the labels. Whoever is doing the "management" should decide what will be the best approach for him.

>  do we use milestones and how do we use them (e.g. to organize a sprint?)

I like the idea to use them for sprints. So we can plan sprints upfront and check whether we could achieve what we planned.
Also it's nice for reporting, as we have a single list of everything we did during the sprint.

>  What is the best way to use the Projects? Should we use one project for one repo or several (as is now the case here)? Currently, the Projects are used in this repo T3DocTeam to categorize the issues.

I like the idea to use them as categories. https://github.com/TYPO3-Documentation/T3DocTeam/projects provides a nice overview.

**Comment by DanielSiepmann** [comment]
During the sprint we decided to use projects to organize issues in projects, e.g. for sprints.
Also each issue and pull request should have one assignee who is taking care of the progress.
