### ISSUE TITLE
manuals.json and extensions.js are partially wrong

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#23]
The files https://docs.typo3.org/typo3cms/extensions/manuals.json and https://docs.typo3.org/typo3cms/extensions/extensions.js are partially wrong.

**Comment by DanielSiepmann** [comment]
@marble will fix this. One possible solution he has is to stop the current script to generate the files.
Instead the old solution will be used again. This is a change from building the lists from TER back to generating files from available files on the server.

**Comment by DanielSiepmann** [comment]
Also the `https://docs.typo3.org/typo3cms/extensions/systemextensions.js` is wrong.

If this file is fixed and used at https://docs.typo3.org/typo3cms/extensions/Index.html, the text and title of the page has to be adjusted.

**Comment by DanielSiepmann** [comment]
This should be fixed by technical relaunch of docs.typo3.org.

Those files will be updated as necessary.
