### ISSUE TITLE
Documentation about image cropping is missing

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#24]
The core provides a way to crop images in backend. The integrator is able to define different ratios and further options.

Currently there is no documentation covering this feature.
- The official change log entry can be found at: https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.6/Feature-75880-ImplementMultipleCroppingVariantsInImageManipulationTool.html
- The TCA Reference already covers the new tca field type https://docs.typo3.org/typo3cms/TCAReference/ColumnsConfig/Type/ImageManipulation.html

The tasks would be:

- [ ] The big picture should be covered in the CoreAPI
- [ ] The Information about editing images should be extended https://docs.typo3.org/typo3cms/EditorsTutorial/ContentElements/Images/Index.html

 

This topic was initiated by (@ Benjamin Amir, @ Michael Schams - from Slack)

**Comment by linawolf** [comment]
Seems like there is no volunteer to work on this
