### ISSUE TITLE
Improve homepage of docs.typo3.org and the glue pages

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/T3DocTeam#27]

**Comment by sypets** [comment]
Several changes were made (see also https://docs.typo3.org/Home/About/News/2019/Index.html#news-2019-05-09):

- Tutorials & Guides: Restructured
- Start page: Tipps about writing docs moved to "Writing Documentation", general tips (e.g. how to get help) added to start page
- [Usage tips](https://docs.typo3.org/Home/About/UsingThisSite/Index.html) added

I would like to close this issue now. Please reopen if you feel it has not been sufficiently handled.

* Related: ["Create layout and content for docs.typo3.org homepage"](#45)
