### ISSUE TITLE
Contact author for possible composer migration documentation

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/T3DocTeam#28]
https://twitter.com/jouschcom/status/1022443119961407490

@marble will contact Αlbrесht Κöhnlеin whether he would like to contribute his writing to the official docs instead of a blog post.

**Comment by mbrodala** [comment]
Also see https://stackoverflow.com/questions/46450764/switch-to-composer-mode-in-running-instance/46450927#46450927

**Comment by DanielSiepmann** [comment]
Closed by https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/pull/25

**Comment by DanielSiepmann** [comment]
@marble this already was finished faster then we thought :)
