### ISSUE TITLE
Improve the app that show the GithubPullRequests overview

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/T3DocTeam#29]
https://docs.typo3.org/services/GithubPullRequests/

**Comment by marble** [comment]
https://probot.github.io/

![image](https://user-images.githubusercontent.com/307057/43505925-ad286bc2-9568-11e8-9caa-36521769c0ba.png)

<hr/>
Monthly newsletter (don't know if it can be found in the web)

![image](https://user-images.githubusercontent.com/307057/43506322-08234e7e-956a-11e8-98b5-cac6aea88c79.png)

<hr/>
https://blog.github.com/2018-07-10-optimizing-open-source-projects-with-github-apps/8

![image](https://user-images.githubusercontent.com/307057/43506060-321bebb0-9569-11e8-818b-55ef8b046521.png)

<hr/>

https://blog.github.com/changelog/2018-07-02-project-review-automation/ 

![image](https://user-images.githubusercontent.com/307057/43506142-79133118-9569-11e8-8bb2-8376e71ce093.png)

<hr/>
https://help.github.com/articles/about-automation-for-project-boards/

![image](https://user-images.githubusercontent.com/307057/43506248-cc966c06-9569-11e8-86f6-87f159fd9020.png)

**Comment by marble** [comment]
Tip: Write `<hr/>` in comments here to insert horizontal rulers. Do not write `<hr>`.

**Comment by sypets** [comment]
a couple of dashes also works, e.g. 

`---`

3 dashes

---

2 dashes
--

...

**Comment by marble** [comment]
ah, didn't know that. Thanks.

**Comment by sypets** [comment]
Do we need an app or can we just use a link for now?

Currently, https://docs.typo3.org/services/GithubPullRequests/ does not work at all, we have lots of other things to do, would be an easy solution for now until someone has the time to put effort into this:

https://github.com/pulls?q=is%3Aopen+is%3Apr+archived%3Afalse+org%3ATYPO3-Documentation+sort%3Acreated-asc

`org:TYPO3-Documentation
`
will show all PR in TYPO3-Documentation.
