### ISSUE TITLE
Implement error pages (404)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#3]
# Problem

Currently, if there is a broken link, the standard Apache Error message gets displayed, without links. You can't click anywhere.

# Solution
Either:

## Solution 3. Additionally, provide 404 page for each manual (where restructuring has been done or is planned)

# Drafts: 

* https://docs.typo3.org/typo3cms/Teams/T3DocTeam/Drafts/PageNotFound.html

**Comment by DanielSiepmann** [comment]
Also relates to https://github.com/TYPO3-Documentation/T3DocTeam/issues/55

**Comment by DanielSiepmann** [comment]
I guess you mean a draft is available at https://docs.typo3.org/typo3cms/Teams/T3DocTeam/404.html ?

**Comment by DanielSiepmann** [comment]
I've copied this to the glue page and it's in place right now: https://docs.typo3.org/404.html
I can also configure this in apache.

```
                # Disabled for now, as generated 404 page has relative non working links
                # ErrorDocument 404 /404.html
                # ErrorDocument 404 https://docs.typo3.org/404.html
```

BUT! The theme uses relative paths (for a reason). This prevents the 404 page to be displayed, as no referenced file (like css) will be found.

We could redirect to the 404, this will work, but creates a 302 instead of a 404...

Also we could move / copy this file fully working somewhere else on the server to work. But this would prevent the deployment. This way each change has to be done manually.

**Comment by DanielSiepmann** [comment]
Current idea, as discussed with @bmack we will try to use a 404.php internal. We will then use the existing 404.html and add a base tag to fix relative includes. Or we replace relative includes.

Also we can add a mapping to provide redirects for known moved documents, this relates to https://github.com/TYPO3-Documentation/T3DocTeam/issues/37.

**Comment by DanielSiepmann** [comment]
The new `404.php` is now in place. It uses the `404.html`, generated from the website repository. Then it will add a HTML-Base tag to fix the relative urls, thanks @bmack for the Idea.

This way the 404 is fully editable and deployable. We even have the "Edit me on GitHub" button.

**Comment by sypets** [comment]
I don't know what the above mentioned 404.php does. Right now, it looks like there is just one general 404 page. 

Having dedicated error page for manuals with lots of changed links / migrated content would improve ux. 

Especially for:

* changelog
* security guide
* inside TYPO3
* fal
* services

Example: In changelog, links have often changed in the past. We now have external URLs which no longer work. Example: on this page: https://techblog.sitegeist.de/responsive-images-with-typo3-8-7/

* [https://docs.typo3.org/typo3cms/extensions/core/**8.7**/Changelog/**8.6**/Feature-75880-ImplementMultipleCroppingVariantsInImageManipulationTool.html](https://docs.typo3.org/typo3cms/extensions/core/8.7/Changelog/8.6/Feature-75880-ImplementMultipleCroppingVariantsInImageManipulationTool.html)

The current error page shown is not very helpful in finding the correct changelog (unless you know where the changelog is).

**Comment by DanielSiepmann** [comment]
We have the path traversal in place. This is also kept with technical relaunch of docs.typo3.org.

Each manual can provide his own 404.html / 404.rst, which is used, falling back to the 404 of docs.typo3.org homepage.
