### ISSUE TITLE
Consider creating a t3-Sphinx domain for TYPO3-specific reST markup

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/T3DocTeam#31]
See:
- http://www.sphinx-doc.org/en/stable/domains.html
- What needs styling? For example: This kind of [property description](https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Uri/Typolink.html#parameters) blocks.

**Comment by linawolf** [comment]
I dont think we will do this
