### ISSUE TITLE
Drafts in T3DocTeam-at-Work shouldn't be indexed by search engines

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#34]
Currently [T3DocTeam-at-Work](https://docs.typo3.org/typo3cms/Teams/T3DocTeam) is being indexed by the search engine (not excluded in [robots.txt](https://docs.typo3.org/robots.txt)).

This is not good, as the drafts in the [drafts section](https://docs.typo3.org/typo3cms/Teams/T3DocTeam/Drafts/Index.html) are indexed as well and appear in the search engine results.

In any case, at least the drafts shouldn't be indexed or moved elsewhere.

**Comment by marble** [comment]
Can you come up with an improved robots.txt?
Currently: https://docs.typo3.org/robots.txt
To be modified at: [repo: robots.txt](https://github.com/TYPO3-Documentation/typo3-docs-typo3-org-resources/blob/master/webroot/robots.txt)?

**Comment by sypets** [comment]
Drafts was renamed to "draft" which is excluded in robots.txt. 

Additionally, we can now use the documentation-draft branch.
