### ISSUE TITLE
Remove version 7 and 8 from changelog

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/T3DocTeam#36]
https://docs.typo3.org/typo3cms/extensions/core/latest/ has two older versions which only have their changes. As master / latest has all versions, we do no longer need the specific versions in version selector.

They only lead to confusion as they are also not updated, as most fixes are provided to master / latest only.

**Comment by marble** [comment]
Done, solved.

Steps were::

<pre>
ssh mbless@srv123.typo3.org

# remove sysext:core from list of extensions that should be rendered
# leave a pointer to this issue
edit ~/HTDOCS/git.typo3.org/TYPO3CMS/Extensions/TYPO3.CMS.ALL-SYSEXT.make_8.7/cron_rebuild.sh
edit ~/HTDOCS/git.typo3.org/TYPO3CMS/Extensions/TYPO3.CMS.ALL-SYSEXT.make_7.6/cron_rebuild.sh

# remove unwanted versions
rm -rf /home/mbless/public_html/typo3cms/extensions/core/7.6
rm -rf /home/mbless/public_html/typo3cms/extensions/core/8.7
</pre>
