### ISSUE TITLE
Find a place for Github typo3/surf documentation

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/T3DocTeam#38]
https://github.com/TYPO3/Surf 

From Slack:

Sebastian Schreiber [10:15 AM]
Hi Martin, i am one of the current maintainers of TYPO3 Surf. We would like to publish our docs under the TYPO3 umbrella. I already generated our .rst-Files successfully locally with the TYPO3-Sphinx-Theme. Would it be possible for us to publish our docs on the offical TYPO3 domain? If so, what do we have to do in order to succeed? (edited)

**Comment by sabbelasichon** [comment]
Hi Martin,
it would be nice if we could check the rendering of the Surf documentation on docs.typo3.org with the following settings:

Please publish: https://github.com/TYPO3/Surf
branch: master
as: surf
preferably at:  https://docs.typo3.org/surf

I already successfully rendered with the help of @DanielSiepmann the Surf documentation on the future infrastructure.

**Comment by sypets** [comment]
Surf is now rendered: https://docs.typo3.org/surf/. So I am closing this.
