### ISSUE TITLE
Rename branch 'latest' to 'master' for all manuals

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/T3DocTeam#39]
This could be part of https://github.com/TYPO3-Documentation/T3DocTeam/issues/11 but may be clearer seen here.

2018-09-25 Done for the 'Installation Guide'.

Steps were:
- create 'master' branch from 'latest'
- push to Github
- set 'master' as default branch in the Github webinterface
- remove 'latest' branch locally and on Github
- update the buildsettings in docs.typo3.org/~mbless/HTDOCS/github.com/TYPO3-Documentation/TYPO3/Guide/Installation.git.make/buildsettings.sh

Additionally:
- Add 'master' as know version to 'ajaxversions.php' and '.htaccess in typo3-docs-typo3-org-resources.git

**Comment by sypets** [comment]
Can someone check out https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-Templating? There is a latest and a master branch. Can **latest** be removed? There is also currently 1 PR in that repo which wants to merge from master into latest. Probably not intentional ...

**Comment by sypets** [comment]
done.
