### ISSUE TITLE
Aspects of global search implementation

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#4]
# Problem
Currently, it is only possible to search in the current manual. Additionally, this is not intuitively clear ("Search this project."). In some case (e.g. the "Home" manual) it might even be considered harmful. 

# Solution
A global search engine will be implemented. It will crawl the documentation and make it available using modern search engine technology (synonyms, stemming etc.)

# Requirements

* It should be possible to search by versions (e.g. only TYPO3 8)

# Prerequisites

* homogenous structuring of manuals, e.g. naming of branches

**Comment by DanielSiepmann** [comment]
@wmdbMattes was on this topic. Can you share us the current state? And a roadmap. Maybe someone can supported you or finish the task, depending on current state.

**Comment by marble** [comment]
I don't want to leave this one unassigned and it shouldn't be closed, I think. Let's collect ideas around this topic here.

**Comment by DanielSiepmann** [comment]
I'm currently working on that, but do not have any timeline planed yet.

I've got all work from mattes and will continue with his work.

**Comment by sypets** [comment]
close in favor of #43
