### ISSUE TITLE
Old version of homepage is online?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#40]
There is an alternative version of "Welcome 2.0" online: https://docs.typo3.org/Overview/Tips.html

![screenshot](https://user-images.githubusercontent.com/13206455/52482726-5020a300-2bb2-11e9-8448-41642be981b5.png)

Some of the links in the left menu go to the main homepage. Some don't and the content looks outdated:

* https://docs.typo3.org/Extensions/Index.html
* https://docs.typo3.org/News/Index.html
* https://docs.typo3.org/Overview/Contribute.html
* https://docs.typo3.org/Overview/ForYourInformation.html 
* https://docs.typo3.org/Overview/PdfFiles.html
* https://docs.typo3.org/Overview/WhatsNew.html

Main problems: 

* Wrong link for repo, so "Edit me on GitHub is a 404 so we cannot edit the pages but they are online. parts of the information is outdated. 
* the pages are being indexed

Additionally, there are several broken links, due to the "Edit me on github" etc. pointing to the wrong repo (for example on https://docs.typo3.org/Extensions/Index.html). So this clutters up the list of broken link (see #37).

**Comment by sypets** [comment]
I just landed on one of these pages again: https://docs.typo3.org/typo3cms/Books.html

Problem: it is not possible to edit these pages. Again, it looks like this is an alternative version of the homepage.

**Comment by sypets** [comment]
Old news: https://docs.typo3.org/Latest/Index.html

**Comment by marble** [comment]
I have cleaned things up for now. Thanks for reporting!

**Comment by sypets** [comment]
Thank you!
