### ISSUE TITLE
Guidelines / best practices / templates for diagrams

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#41]
There is a question / discussion about this in Slack: https://typo3.slack.com/archives/C028JEPJL/p1541665064145200

This issue is used for diagrams (e.g. UML diagrams, System architecture etc.), usually created with UML tool / as vector graphics. There is _https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/issues/11_ about augmenting screenshots with numbers, arrows, etc. We handle that separately. 

### Tools

- PlantUML

### Formats (source / rendered)

- .plantuml (source) : plain text format, good for UML diagrams
- .svg (source + rendered) : vector graphic
- .png : e.g. for screenshots

### How to collaborate / add source of image

- Upload source **and** compiled image to git repo (e.g. .plantuml, .svg)?

## Example images

   - [TYPO3 explained: FormEngine workflow sequence diagram](https://docs.typo3.org/typo3cms/CoreApiReference/_images/FormEngineMainWorkflow.svg)
   - [TYPO3 explained: system overview](https://docs.typo3.org/typo3cms/CoreApiReference/singlehtml/_images/Typo3CmsStructure.png)
   - [TYPO3 explained: class diagram](https://docs.typo3.org/typo3cms/CoreApiReference/_images/FormEngineRenderTree.svg)

## More information

- Information from [Daniel Siepmann: Docs / Phinx / PlantUML](https://daniel-siepmann.de/Posts/2016/06/11-read-the-docs-sphinx-plantuml-workflow.html)

## Related

* [Issue about adding more diagrams to TYPO3 Explained](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/221)
* [Issue about creating images from screenshots augmented with arrows, number, boxes, etc.](https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/issues/11)

**Comment by sypets** [comment]
Closing here in favor of https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/issues/11

**Comment by sypets** [comment]
Reopen because

**Comment by DanielSiepmann** [comment]
I've added two diagrams in the meantime:
* https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/RequestHandling/Index.html#typo3-implementation
* https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/10-Outlook/6-dispatching.html

We should find a clean way, e.g. add plantuml to docker container and provide also a configuration and automatic conversion within container.

Right now I'm running a pre compilation from plantuml files to svg files beforehand, with my own configuration to have TYPO3 colors in place.

**Comment by sypets** [comment]
Help is under way with plantUML so I am closing this.
