### ISSUE TITLE
Find redirect solution for the Security Guide

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/T3DocTeam#42]
https://github.com/TYPO3-Documentation/T3DocTeam/issues/37#issuecomment-439164801
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/37

**Comment by marble** [comment]
①
Current, suboptimal contents of ~/public_html/typo3cms/SecurityGuide/.htaccess:
<pre>`Options +Indexes
# Fix broken search in the singlehtml versions
# If searching, bring the user away from the singlehtml
# (where the search would only give an error 404) and direct him to the default version.
# See https://forge.typo3.org/issues/60838
RedirectMatch permanent (.*)/singlehtml/search\.html $1/search.html
RewriteEngine On
RewriteRule (GeneralInformation|TypesOfThreats|HackedSite|Backups|Introduction|SecurityTeam|GeneralGuidelines|GuidelinesAdministrators|GuidelinesIntegrators|GuidelinesEditors)(.*) https://docs.typo3.org/typo3cms/CoreApiReference/Security/$1/  [R=301,L]
RewriteRule singlehtml(.*) https://docs.typo3.org/typo3cms/CoreApiReference/singlehtml/ [R=301,L]
RewriteRule (stable/)?(.*) https://docs.typo3.org/typo3cms/CoreApiReference/$1Security/$2 [R=301,L]

# Do not rewrite URLs starting with any valid version number followed by a slash
RewriteRule ^(([0-9]+)(\.[0-9]+)(\.[0-9]+)*)/(.*)$ -  [L]
# Do not rewrite URLs starting with the provided words
RewriteRule ^(latest|packages|stable)(.*)$ -  [L]
RewriteRule ^manuals.json(.*)$ -  [L]
# Rewrite the rest into the folder stable/
RewriteRule ^(.*)$ stable/$1
</pre>
②
I have disabled that .htaccess: `mv .htaccess .htaccess.timek.htaccess`
③
I have enabled the current default .htaccess which should be used in all base folders of a manual:
`ln -s ~/scripts/config/_htaccess-2016-08.txt .htaccess`
④
This is the contents of the standard .htaccess of 2016-08:
<pre>Options +Indexes

RewriteEngine On

# Do not rewrite URLs starting with any valid version number followed by a slash
RewriteRule ^[0-9]+(\.[0-9]+)(\.[0-9]+)*(-dev)?/(.*)$ -  [L]

# Do not rewrite URLs like '8-dev/'
RewriteRule ^[0-9]+-dev/(.*)$ -  [L]

# Do not rewrite URLs starting with the provided words
RewriteRule ^(latest|master|packages|stable)(.*)$ -  [L]

# still needed?
RewriteRule ^manuals.json(.*)$ -  [L]

# Rewrite other cases into the folder stable/
RewriteRule ^(.*)$ stable/$1
</pre>

**Comment by marble** [comment]
This ticket is waiting for somebody willing to invest time. Otherwise I'll close it some time soon.

**Comment by sypets** [comment]
Please don't close.

**Comment by sypets** [comment]
I do think the above rule should have worked:
`RewriteRule (GeneralInformation|TypesOfThreats|HackedSite|Backups|Introduction|SecurityTeam|GeneralGuidelines|GuidelinesAdministrators|GuidelinesIntegrators|GuidelinesEditors)(.*) https://docs.typo3.org/typo3cms/CoreApiReference/Security/$1/  [R=301,L]
`
(https://github.com/TYPO3-Documentation/T3DocTeam/issues/42#issuecomment-439168108)

**Comment by DanielSiepmann** [comment]
Let's proceed within https://github.com/TYPO3-Documentation/T3DocTeam/issues/37
