### ISSUE TITLE
Create rendering automization for Bamboo

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/T3DocTeam#44]

**Comment by DanielSiepmann** [comment]
The issue handling is handled within TYPO3 GmbH Jira: https://jira.typo3.com/projects/DOCS/issues/ as it's completely inside the GmbH infrastructure.

The current rendering is available within TYPO3 GmbH Bamboo: https://bamboo.typo3.com/browse/CORE-DR

The plan is to provide a simple hook for repositories, which will call Intercept, which will prepare a request to run a Bamboo Job.

This will fetch the repository, render the documentation using the official docker image and deploy it to the new server, right now the new staging server.

The Server Team has a Request to prepare the new production server, with minimal requirements.

Right now it's already planned to have a small PHP Application on the new server. This can handle indexing for #43, re rendering via Web UI and further stuff to come.

**Comment by sypets** [comment]
I think we can officially declare this as finished. Some more documentation is still being added ...

Please reopen or create new issue if you disagree.
