### ISSUE TITLE
Bug: Extension fp_newsletter not rendered

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/T3DocTeam#46]
https://typo3.slack.com/archives/C028JEPJL/p1542273351213000?thread_ts=1542273204.212900&cid=C028JEPJL

**Comment by marble** [comment]
Proceedings:
Verified: The extension - including the german localization - is rendered perfectly by the Docker container.
Let's assume an error in the deployment part when uploading the final result.

**Comment by marble** [comment]
Tracked down the error:
- The docs are rendered perfectly
- deployment isn't working: de-de not copied, symlink to stable not created, symlink to .htaccess not created for the localization.

It's manually published though: https://docs.typo3.org/typo3cms/extensions/fp_newsletter/de-de/0.9.10/

**Comment by linawolf** [comment]
Seems like this was solved
