### ISSUE TITLE
Create a "Contribute your tutorial" platform in TYPO3 documentation

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/T3DocTeam#48]
- https://tutorials.ubuntu.com/
- https://codelabs.developers.google.com/codelabs/your-first-pwapp/#0
- https://typo3.slack.com/archives/C028JEPJL/p1542810190246700

**Comment by alexander-nitsche** [comment]
This idea is related to the Planet TYPO3 project, that wants to aggregate news from any privately hosted blog in a single public domain, e.g. planet.typo3.org. So this is more a "Make your tutorial public" platform using Judo. See

1. https://notes.typo3.org/planet-aggregator
2. https://typo3.slack.com/archives/C02FDLA36GH (Slack channel #t3o-planet-typo3)
3. https://github.com/Crell/Planedo

**Comment by linawolf** [comment]
Not the job of the documentation team, really
