### ISSUE TITLE
Find solution for broken links

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#5]
# Problem 

When restructuring a manual, the URLs will change.
This impacts indexed URLs from search engines, e.g. Google and Bing, but also Websites like Blogs and Bookmarks or chats.

# Solutions

One or more of the following solutions can be used:

## Solution 1: Relocator service (Martin)

https://docs.typo3.org/typo3cms/Teams/T3DocTeam/PersonalNotes/Marble/IdeaRelocatorService.html

### Soluation 2a : redirects with redirect map + git repo (to enable PR)

As suggested on Slack by @tmotyl

https://typo3.slack.com/archives/C028JEPJL/p1537521583000100

## Solution 3: 404 page (which includes links)

See #2, #3

**Comment by DanielSiepmann** [comment]
Do we have more information about Solution 1? I don't know this one.

**Comment by sypets** [comment]
@marble wrote something about it, but the last time I checked the link to the information was broken.

**Comment by sypets** [comment]
@DanielSiepmann Found it: https://docs.typo3.org/typo3cms/Teams/T3DocTeam/PersonalNotes/Marble/IdeaRelocatorService.html

**Comment by DanielSiepmann** [comment]
Thanks. I know there is a way to retrieve all the link anchors from the inventory file for a rendered manual.
So in case we want to provide the service, we have to fetch the anchor from the url. I do not know how easy this will be. E.g. `https://docs.typo3.org/typo3cms/TyposcriptReference/Conditions/Reference.html#dayofyear` will link to `.. _condition-dayofyear:` within `Conditions/Reference.txt`. But maybe the inventory file allows easy mapping. This would be cool as we could ad proper redirects without any further manual work.

**Comment by DanielSiepmann** [comment]
We decided to go with solution 2. When restructuring manuals, we will write rewrite rules in the Webserver configuration.

**Comment by DanielSiepmann** [comment]
Also the 404 might be

**Comment by sypets** [comment]
see also discussion on slack: https://typo3.slack.com/archives/C028JEPJL/p1537518683000100

**Comment by sypets** [comment]
Three issues open for broken links. Closing this one. See #37
