### ISSUE TITLE
Find answer: Server srv123 - Is there a technical solution for redirects right now?

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/T3DocTeam#55]
In a follow up talk yesterday @stucki indicates that there might be an easy way to create and maintain redirects for the docs server right now. I heard the word "proxy".
The docs server at the moment still is a very old Debian at srv123.typo3.org and we are trying to move away from that server as soon as possible.

Is redirecting possible? How?

I will point the server team to this issue.

#5, #37, #42

**Comment by stucki** [comment]
Thanks for asking me!

We checked that today during our team meeting and realized that it is not possible right now. There's a central proxy server for many sites of the `*.typo3.org` domain where we can add redirects if that is needed. However, `docs.typo3.org` is currently not accessed through it (compare DNS of `docs` with the destination for `extensions`, `forge` and `git`).

We can change that, but it requires additional planning...
Generally, adding redirects on the proxy is more complex and should be avoided.

But what's the problem with adding the redirects to the `.htaccess` file in your document root? That's https://github.com/TYPO3-Documentation/typo3-docs-typo3-org-resources/blob/master/webroot/.htaccess as it seems to me.

Rules should be added at the bottom of this file. Here's an example which is untested but should work:

```
# https://github.com/TYPO3-Documentation/redirects/blob/master/redirects-fix.csv
# https://github.com/TYPO3-Documentation/redirects/blob/master/redirects-var-fix.csv
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(typo3cms/.*)/Index.html /$1.html [R=301,L]

# https://github.com/TYPO3-Documentation/redirects/blob/master/redirects-var.csv
RewriteRule ^typo3cms/extensions/core/7.6/Changelog/ /typo3cms/extensions/core/latest/Changelog/ [R=301,L]
```

This should solve all issues which are currently listed in https://github.com/TYPO3-Documentation/redirects.

If this does not work, I can also offer my help to take care of the change...

**Comment by sypets** [comment]
I agree, a number of broken links could be fixed right now by adding redirects to the .htaccess files. I find this increasingly frustrating and broken links are being reported again and again, see[Slack](https://typo3.slack.com/archives/C028JEPJL/p1545993191021600)

Who has access to the server and it willing to regularly take care of that?

Can we get a consensus with t3doc maintainers to add redirects when restructuring?

Can we add ErrorDocument to some of the main manuals that have been stripped down (Security Guide, FAL), so you at least get an error page with some links on them. See my proposal in #3

**Comment by stucki** [comment]
I wrote down here how it can be fixed. I also offered help to take care of it myself. I do have access to this system, however it's owned by the documentation team, so they should at least approve the changes...

**Comment by sypets** [comment]
Three issues open for broken links. Closing this one. See #37
