### ISSUE TITLE
Create automated tests for code snippets?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#69]
This has been raised as idea in Issue ["How these docs should be done"](https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/issues/64).

I realize the Pygments already does some syntax checking of the code snippets. However, currently, the code is simply not highlighted. And an error is not logged, as far as I know. 

Maybe we can check if it is possible to:

* add automated scripts to test code snippets
* have this integrated into GitHub as pipeline for PR
* ditto for core development

**Comment by alexander-nitsche** [comment]
Part of this issue is solved with the automatic extracting of code from the code base to the documentation with the [TYPO3 Screenshots](https://github.com/TYPO3-Documentation/t3docs-screenshots) tool.

**Comment by sypets** [comment]
@alexander-nitsche From my end we can close here.

**Comment by sypets** [comment]
Closing.
