### ISSUE TITLE
Update the docs before we release the new version.

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#70]
Copied from an issue with several suggestions: https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/issues/64

> Create a full clone of this document for every new framework version, update the docs before you release the new version.
...
See the Python docs as a reference.

I agree:
* we should not have docs online that are unfinished, outdated. 
* It would be great to release a new version of the docs with the next TYPO3 release (not add chapters for the new stuff **after** it is released or way after it is released)

How can we do this?

Related:

* [How can we get changes added to documentation early? And what is master: master or latest release?](#133) (issue 133)
* [Add information when manual (or page) was last reviewed and what state it is in (e.g. up-to-date for version ...)](#73) (issue 73)
* ["These docs are inconsistent"](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/430)
* ["Question: How to deal with Changelog becoming main documentation for some new features?"](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/418)

**Comment by sypets** [comment]
One possibility would be to:

1. latest (or master) is always latest released version - currently 9.5
2. As soon as version 10 comes out, we create a new branch, but this gets rendered in drafts area. We already have a drafts area https://docs.typo3.org/typo3cms/drafts/ that is not indexed by search engines
3. A list of draft branches can be maintained.

**Comment by susannemoog** [comment]
@sypets I'm trying to grasp this bunch of related tickets. In general, we are currently at the point where the docs are up-to-date for each release, so at least this part of the topic can probably be closed?

**Comment by sypets** [comment]
Closing.
