### ISSUE TITLE
Question: How to deal with Changelog becoming main documentation for some new features?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#75]
Changelog is increasingly becoming main core documentation (for new features).

Using Changelog to document new features (and not move information after it has been merged) has disadvantage that it is more difficult to find things in other places (e.g. use search in "TYPO3 Explained"). Sometimes links are added to Changelog in main documentation. 

Shouldn't rather most information for new features be in main documentatio? How should this be handled in general?

# Possible solutions / approaches / to be decided

For some of these points it is only relevant if a Changelog extensively documents a new feature.

* Do not change changelog at all. 
* Add link in main manual to changelog Example: [routeEnhancers](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/SiteHandling/Basics.html#routeenhancers)
* **Do not change changelog**, but add link from changelog to section in other manual, once that has been added. 
* Choose duplicate content: if things are explained extensively in Changelog, more or less **copy** information in main manual
* **Move** extensive information from changelog to main manual and add link in changelog 

# Examples:

* [Routing Enhancers](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.5/Feature-86365-RoutingEnhancersAndAspects.html). This actually has section in "TYPO3 Explained", but just links to changelog: https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/SiteHandling/Basics.html?highlight=routing#routeenhancers. **Disadvantages**: 
  * searching for _routing enhancers_ in "TYPO3 Explained" yields no results. Searching for _slug_ yields no results. The search does not work very well in general, but in this case it should get hits. 
  * Difficult to find information about routing / URL handling in main navigation in "TYPO3 Explained"
  * If information is directly in "TYPO3 Explained" or other reference, you have more context, you can click on start page of chapter. In Changelog you have one mosaic piece without context and no introduction to subject

**Comment by pixelbrackets** [comment]
Thanks for raising this question. My two cents:

A log is a log. It should be considered immutable. The main docs however should be changed &  enhanced continually. Therefore both need to exist. And it is absolutely okay to have duplicate content in these documents up to some degree.

The changelog should be concise (you mentioned the extension scanner → as a developer I want to to the able to skim the information) and may contain links to further information.

The main docs should not contain links to the changelog to explain something. This imho encourages cluttered documentation and a "single feature only" documentation style. We however want to describe components and workflows as a whole. With changes! Links should only be set to if the Changelog contains information about the motivation for this change.

Workflow from my perspective:

- Concise information in changelog
- Copy and outline information in main docs
- Add link to main doc in changelog

**Comment by sypets** [comment]
@pixelbrackets I agree! What you wrote was very helpful for me. Thank you.

I opened a ["decision" topic](https://decisions.typo3.org/t/handle-changelog-vs-main-documentation-for-features/518) about this. (A decision category "documentation" was recently added to decisions.typo3.org. We can now handle decisions there.)

The goal of opening the decision topic is to hear some more thoughts and then make final decision.

The decision proposes what you basically said: Do not change Changelog (immutable). Add information to main docs. Do not link to Changelog.

**Comment by sypets** [comment]
Has been dealt with in [decision](https://decisions.typo3.org/t/handle-changelog-vs-main-documentation-for-features/518).
