### ISSUE TITLE
Question: Should more links be added to Changelog?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#76]
## Current problem

There are some Changelogs that are related to others. Often, there is first a deprecation, and then a removal. Sometimes one Features is introduced which involves a breaking change. Often, it would be helpful to jump directly to the main documentation (e.g. TCA reference, TYPO3 Explained, ...) for further reading. 

Examples:

* [Breaking: #77987 - Removal fe_users rendering in page module](https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.4/Breaking-77987-RemovalFe_usersRenderingInPageModule.html), refers to another changelog entry: "Because of the deprecation of $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['cms']['db_layout']['addTables'] ..."

## Possible solution

If intersphinx links are used (`:ref:`), these can be used to link to other changes and a place in the official documentation.

## Problem with this solution

The changelogs are often read as plaintext, both in the Extension Scanner and in "View Upgrade Documentation". Inserting links with `:ref:` would make text less readable and provide no use, because the link can neither be clicked, nor copy-pasted. 

What we could do though:

* Add a link for both extension scanner and "View  Upgrade Documentation" that links to the rendered changelog
* Put the extra links on the bottom of the page, as is done for example here: https://review.typo3.org/c/Packages/TYPO3.CMS/+/60347

```
Related
=======

- :ref:`Deprecation-82254-DeprecateGLOBALSTYPO3_CONF_VARSEXTextConf`

More Information
================

- :ref:`t3coreapi:extension-options`
```

https://review.typo3.org/c/Packages/TYPO3.CMS/+/60347/2/typo3/sysext/core/Documentation/Changelog/9.0/Feature-82254-StoreExtensionConfigurationAsPlainArray.rst

## Goal

Links will serve as glue for otherwise fragmented information

## Related

* [Question: How to deal with Changelog becoming main documentation for some new features?](https://github.com/TYPO3-Documentation/T3DocTeam/issues/75)
* core: [Add Links from Changelog to documentation](https://forge.typo3.org/issues/88018)

**Comment by susannemoog** [comment]
I would not add links between changelogs. The deprecation / breaking combinations are easy enough to find and targeted at developers. For everyone else the main docs should be the go to place, not the changelog. I don't think the benefits linking has are worth the work.

**Comment by sypets** [comment]
I am closing this now.

Should probably be decided in the core anyway and I don't think it will be decided to do this.
