### ISSUE TITLE
Clarify terms and use them consistently, possibly add glossary (terminology)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#77]
Topic: term, term definition, glossary

Things can be confusing if terms are used inconsistently, e.g. same term used for different things or various terms used for one thing. 

This is especially problematic if these things are used in the beginner tutorials and tools or if terms are used differently in the documentation and in the source code or backend.

## Terms to clarify

content elements:

* [ ]  **Content Elements, Plugins**: difference is not clear, sometimes used in different ways, e.g. "content elements" for general content elements (including plugins) and "content elements" for content elements that are not plugins
  * proposed solution: "Content Element" is the general term, a content element can be a plugin
  * see [discussion on Slack](https://typo3.slack.com/archives/C8Z2UM50Q/p1583306304120300)
  * see [discussion on Slack](https://typo3.slack.com/archives/C8Z2UM50Q/p1653375747041509)

* [ ] **Content Elements** is used for "Content Elements" (record in tt_content) and for "Content Element Type" (type of Content Elements)
  * proposed solution: use "content element type" for the type
  * update (May 27, 2021): [Benni Mack: use "Content type" for this ](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1876#issuecomment-1139556490)

TypoScript

* [x] **Content object Types** in TSref: same as previous point: chapter "Content object" actually describes "Content object Types". Also cObject is sometimes uses for content object type and sometimes for "content object", see also [this other issue in TSref](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/issues/229)

* [x] **TypoScript** is used for "TypoScript syntax" and "TypoScript Templates", see [decision](https://decisions.typo3.org/t/clarification-of-term-typoscript/560/5)

* [ ] we usually say constants use "TypoScript syntax" but the syntax for constants is slightly different, generally it is a subset of TypoScript syntax but it also has the declerative comment (see next point). Do we call it **"TypoScript constant syntax"**?

* [ ] what do we call the "comment" in constants and extension configuration which defines category, type etc. suggestion: **"constant declaration"**

```
# cat=content/cText/1; type=; label= Bodytext font: This is the font face used for text!
face =
```

----

* [ ]  **extension / distribution / package / sitepackage**:  terms are not always used in a consistent way
   * [TYPO3 cms-base-distribution](https://packagist.org/packages/typo3/cms-base-distribution) : it is called distribution
   * In TYPO3, a distribution is something specific: "Distributions are full TYPO3 CMS websites ready to be unpacked" as described in [TYPO3 Explained: Creating a new distribution](https://docs.typo3.org/typo3cms/CoreApiReference/ExtensionArchitecture/CreateNewDistribution/Index.html)
  * "Introduction Package" is called a package
  * The word "package"  is used in the [Installation & Upgrade Guide](https://docs.typo3.org/typo3cms/InstallationGuide/In-depth/WhichPackageAndFormat/Index.html) to refer to the TYPO3 source package. But "package" has another - different - meaning.

* [ ] **"Extension Configuration"**: usually refers to ext_conf_template.txt, [ExtensionConfiguration API](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Feature-82254-StoreExtensionConfigurationAsPlainArray.html), $GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']. 
  * In sitepackage tutorial, "Extension Configuration" is used to describe the files ext_emconf.php etc. 
  * in "TYPO3 Explained", the chapter for "Extension Configuration" is used to mean, general extension configuration things, and also to mean the specific kind of extension configuration in (since TYPO3 9) in $GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS'] 

* The terms **settings**, **preferences** and **configuration**.We should maybe write down what each terms mean and where it is used. In the backend, there are 2 modules: "Settings" contains settings that can be changed in the backend. "Configuration" makes it possible to view configuration variables. There are "Configuration files" (ext_tables.php and ex_localconf.php) and "Extension Configuration" which actually refers to something that can be changed in settings. In general, we can differentiate between static configuration, e.g things that are used to setup the system and cannot be changed by the "user" (be user or admin) and "settings" that include the configuration that can be changed (this is usually a subset of configuration). Be clear about how the terms **configuration, settings, setup, preferences, options, configuration options** etc. are used. 

## Related issues, decisions

* Decision: [TypoScript](https://decisions.typo3.org/t/clarification-of-term-typoscript/560/5)
* [Make „cobj” „cobject” „content object” less confusing](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/issues/229)
* https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1384

## Already existing lists

* Glossary in Wiki: https://wiki.typo3.org/De:Glossary
* Terminology in Wiki: https://wiki.typo3.org/Translations/Terminology_Project#Build_a_common_Treasury_of_Words
* Spelling & Preferred Terms in "Writing Documentation": https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/Glossary.html
 

## Resources for what terms to use for what

configuration / setup / settings / options / preferences:

* https://www.quora.com/What-is-the-difference-between-the-words-setting-and-configuration-in-the-context-of-software-industry
* https://english.stackexchange.com/questions/59058/what-is-the-difference-between-options-and-settings/59072
* https://ux.stackexchange.com/questions/17442/options-preferences-settings-configurations-what-to-call-them-in-my-applicat
* https://stackoverflow.com/questions/2074384/options-settings-properties-configuration-preferences-when-and-why

**Comment by liayn** [comment]
Do we have a common usage of the words "Backend" and "Frontend"? Afaiks this varies a lot as well.
- backend
- Backend
- back-end

**Comment by sypets** [comment]
@liayn If you just mean the spelling, that was clarified a while ago, see ["Spelling & Preferred Terms Reference"](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/ContentStyleGuide.html#spelling-preferred-terms-reference) in Writing Documentation

> backend
> Usually not capitalized. 


But I'll admit, that is not always used consistently.

**Comment by liayn** [comment]
Ah cool. Wasn't aware of that. Perfect.

**Comment by sypets** [comment]
Discussion about terms and definitions for "content element" and "plugin" in [Slack](https://typo3.slack.com/archives/C8Z2UM50Q/p1583306304120300).

**Summary**:

* plugin is a type of content element
* we might use "content plugin" in the docs (to differentiate from the generic word "plugin") or "content element of type plugin"
* content elements can have various types, e.g. text, images, list of files, plugin or more (which can be created as new custom content element types)

**content element:**

> **Content elements are records that allow to display information in a page,**
> **The contents are stored in table tt_content**
> **A content can have different types: text, images, list of files, etc. or plugin.** 

**difference**:
> a classic simple content element uses the controller and action of the template engine/ rendering definition (e.g. fluidstyled_content) while a plugin uses its own controller and action. A plugin can be of the CType list with an own list_type , but it can also be an own CType.

>  a content element is a tool to edit content directly where it is placed, while a plugin displays an aggregation of (generic) content from a different source (e.g. news folder or imported data).

**plugin is:**
> It's a type of content element ("Plugin") bundling dynamic or interactive content.  The content output by the plugin is not normally cached on a content element level, but the plugin itself caches its output.

> A content plugin is a specific type of content element. In addition to supporting everything a content element supports, it also facilitates dynamic rendering, as opposed to standard content elements which facilitate only static rendering" 

> I don't think it's that difficult to explain or understand, and I don't think it needs a different term than "plugin" except maybe to preface it with "content plugin" to clearly indicate it "renders content"

**problem with term plugin:**

> So I would agree, **don't let us rename plugin, just define what plugin means most of the time**

**about plugin is dynamic, content element not:**

this approach is misleading:

> well, what does dynamic mean? For example you can use cObject and fire up whatever you want in all content elements using fluid.
Also each content element could use a userFunc. Which doesn't make any difference to a plugin.
Also a plugin is not only there to aggregate data. It can also just integrate data from somewhere else, or display static stuff. And you could do stuff from plugins via dataprocessors most of the time as well.
For me a real plugin consists of multiple different php methods that can be triggered from outside, just as written by rupasix already.

**general considerations:**

* if we change the term plugin we would also have to change core API

> even if we can say that a plugin is a content element type, we shouldn't confuse readers with CType or list_type details

> for documentation I would try to find terms (at least for "plugin") that are more self-explanatory, but however add the word "plugin" to the glossary and describe, what people are referring to if using this word in the context of TYPO3.

> How about "dynamic content element"?
> In the first blueprint about structured content elements I did together with `cd` we tried to avoid using terms that have been used by specific extensions already - so "Flexible Content Elements" or "Dynamic Content Elements" or "Gridelements" should not be used to avoid confusion

**Comment by alexander-nitsche** [comment]
Note: once we have setup a map of old to new terms, we can use the t3docs-tools to easily search and replace and commit and push across all repositories and release branches: https://github.com/TYPO3-Documentation/t3docs-tools#exec-repossh.

**Comment by sypets** [comment]
Not so sure about these huge issues anymore which never seem to get done. Seems a bit demotivating. 

I can look at the checklist above again and try to check off some more.

**Comment by sypets** [comment]
Status update: I made contact with structured content group. Will try to work on some more definitions (for the content / plugin). We don't really have a glossary right now (as far as I am aware - the one in "Writing Documentation" lists just the spelling, not the definition), but once a good text for a definition is found, this can be added to the main page for that particular item. There are several things concerned: term disambiguation (term is used fuzzy or with several meanings), finding one preferred term if there are several, using consistent spelling etc.

**Comment by linawolf** [comment]
We do have a glossary by now
