### ISSUE TITLE
Streamline information about composer, composer.json, etc. 

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#84]
Information about Composer could be added in some places, unified, deduplicated and cross-linked. 

* [ ] Perhaps, have one page as landing page where you can generally link to. This page should give a short introduction and have links.
* [ ] Have a sample composer.json for a site (or several examples), for example in "Installation Guide"?
* [x] a sample composer.json for an extension already exists in: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html
* [x] move information from Wiki: https://wiki.typo3.org/Composer
* [ ] cross-link to https://get.typo3.org/misc/composer/helper (link to helper from docs, link to docs from helper)
* [ ] point out differences between TYPO3 versions
* [ ] what about composer.typo3.org? This partly duplicates the documentation.

## Already existing information

* A good introduction is currently in the wiki: https://wiki.typo3.org/Composer
* Information about composer is already available in: Installation & Upgrade Guide
* composer.json for an extension in TYPO3 Explained: Extension Architecture: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html
* composer.json in combination with documentation: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/DirectoryFilenames.html#composer-json
* https://composer.typo3.org
* helper for creating a site composer.json : https://get.typo3.org/misc/composer/helper

**Comment by sypets** [comment]
Some additional points have been raised in https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/pull/97. 

@rowild
>Question: Do you have plans to mention the possiblity to prepare a composer.json that includes all the packages needed? (Some extensions bring examples of such setups, e.g. aimeos, and also the ddev video tutorials presents such a composer.json, but in v8 [with the extra key].) IMO it should be mentioned and it should be pointed out clearly that there are important differences between v8 and v9. Also, it should be explained that only typo3/minimal is a valid preset, but typo3/full and typo3/default are (currently) not (see this page, which could easily create confusion: https://get.typo3.org/misc/composer/helper).

I have added them to the description above.

**Comment by sypets** [comment]
Also, @pixeldesu has worked on Composer documentation / Wiki.

**Comment by pixeldesu** [comment]
@sypets I wrote a version of the "Composer" wiki page with adjustments to newer versions and cross-links in RST. It currently resides in a file outside any repository.

I can open a PR for it, but I don't know which documentation set it belongs into. If you have a suggestion I can put the Composer information there.

**Comment by sypets** [comment]
@pixeldesu That sounds great. Where to put it? Not so easy. That depends on what is the main focus. 

For information about creating a site composer.json and using Composer in a site, we already have [Installation Guide](https://docs.typo3.org/m/typo3/guide-installation/master/en-us/) and some chapter about migrating to Composer and using Composer

For creating a composer.json for your extension we have [composer.json](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html) in "TYPO3 Explained".

If your page is similar to the [current Wiki page on Composer](https://wiki.typo3.org/Composer), it would be a good introduction, explain some concepts etc. I think that deserves a section by itself, but where to put it? I am currently unsure. Can you add a link to your text so we can look at it in detail?

Currently, "TYPO3 Explained" is the manual that explains concepts. That would be the best fit from my point of view. We could either put it in the API Overview (which is already exploding) or create an entire new chapter (as already done for testing and security). That slightly depends on how much text you have.

So, please add a link (or create a PR in T3'Explained) and we should get some more people to weigh in on this decision. Thanks for taking the time and persevering with these issues!

**Comment by pixeldesu** [comment]
@sypets Thanks for the hints, and I'll create a PR to TYPO3 Explained as soon as I'm able to, I was attending T3CON and I'm on vacation now, which delayed my reply a bit.

I put up my current write-up in a Gist:
https://gist.github.com/pixeldesu/658e38e1712af04b40aa1a1dcba85bb5

**Comment by sypets** [comment]
Closing this now. A number of changes have been made to installation guide, content migrated from Wiki etc.
