### ISSUE TITLE
What content is missing in the documentation?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#85]
This is a general issue, where people can make requests for adding new content. 

Just add your suggestion as a comment. 

---

Some things might be better as blog posts, some in docs.typo3.org. Maybe there is already a blog post and it would be good to migrate the contents to docs.typo3.org.

(Of course, we will always ask the authors for permission for cases like these).

---

**Comment by sypets** [comment]
When to use Extbase, when not to? For example persistence / performance considerations, see [Slack](https://github.com/TYPO3-Documentation)

**Comment by sypets** [comment]
From Slack channel:

[StandaloneView](https://typo3.slack.com/archives/C025BQLFA/p1582126800086400) (Fluid):

> in my custom Extension: Is there a way I can create/render a Partial-Template from a Helper/Utility Class? ( in general: outside of controller )
> Yes, you can use the StandaloneView for this.
> I'd send you a doc/example but apparently there is none. :confused:

**Comment by kaystrobach** [comment]
See here: lower part

https://www.derhansen.de/2018/02/multiple-localized-fluid-standalone-views-in-one-request.html

**Comment by sypets** [comment]
**Update**: was taken care of

----

Symfony Console commands already has documentation: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/CommandControllers/Index.html

Does it need improvement?

> It is really fast, to write a #TYPO3 task for the scheduler with the new #Symfony Console Command possibility! 😍
Official docu is not the great ATM (missing all the use statements), but there are great resources you might find interesting, e.g.: https://typo3worx.eu/2019/01/symfony-console-in-typo3/

From Twitter: https://twitter.com/HiddenTraxTYPO3/status/1226108604257832961

**Comment by sypets** [comment]
I think it is better to create individual issues. I created TYPO3CMS-Reference-CoreApi#802
