### ISSUE TITLE
Address the "having to click through empty menu start page problem" (Index.rst with toctree)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#88]
We commonly have a page (Index.rst) with several subpages. This can be the startpage or a page on a sublevel of the menu.

If we have a page, with a toctree, you cannot add headers. Otherwise the pages in toctree will be subpages of the last header (in the menu). 

This has already been [explained by Martin](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/MenuHierarchy.html#how-it-works)

What we have now, if we use the "fixed example"  is an Index.rst in a menu with a toctree but no subheaders. Often people create almost empty Index.rst. People have to click through almost empty pages. 

What we can do instead is put everything on one page, e.g. in Index.rst. Using subheaders (instead of toctree) will create the identical menu, but more will be on a page. This has often been done during the migrating to "TYPO3 Explained". But this can also be confusing. Where does one part begin and the other end?

We now have these solutions:

1. Index.rst with toctree and no subheaders. ("almost empty index page")
1a: with no table of contents (toctree :hidden:). Example: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/GlobalValues/Index.html
1b: with table of contents: Example: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Typo3CoreEngine/Index.html
2. Index.rst with no toctree and several subheaders ("all on one page"). For example Readthedocs does this [here](https://docs.readthedocs.io/en/stable/webhooks.html#using-the-generic-api-integration): everything in chapter "Webhooks" is on "Webhooks"

I think we should figure out what is best and document this as best practice. See what are the pros and cons and if we can overcome the cons. 

Related:

* [Define general structure of a manal](#6)
* [Decide on structure of "TYPO3 Explained" manual](#421)
* [Improve user experience](https://github.com/TYPO3-Documentation/TYPO3CMS-Example-ExtensionManual/issues/12) - this addresses not enough information on start page problem (in contract so not enough information on menu start page), but it is similar

**Comment by sypets** [comment]
After talking with Lolli: This is already common practice when restructuring, e.g. "TYPO3 Explained":

* Use Name.rst rather than Name/Index.rst if only one file
* Do not create ultra short pages: put everything on one page. No more click-to-death.
* **But**, do not blindly follow these rules: use common sense. 

Todo:

* [ ] Document this as "Best Practice"
* [ ] Find more "ultra short pages" and fix. (add redirects)

**Comment by sypets** [comment]
This is also handled in current decision: https://decisions.typo3.org/t/how-to-structure-content-on-a-page/664/2

**Comment by linawolf** [comment]
Much has changed since this issue was opened. I think it improved
