### ISSUE TITLE
Fluid: Think about railroad diagrams

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/T3DocTeam#90]
Getting Fluid syntax right isn't easy. Is it feasable to create railroad diagrams for Fluid? Is the syntax well defined enough? 

Maybe something to talk about with @bmack somewhen.

Example:
- https://www.json.org/ ![grafik](https://user-images.githubusercontent.com/307057/43196012-efb72b98-9006-11e8-9ca2-4b792c922072.png)
- http://bottlecaps.de/rr/ui
- http://mbless.de/blog/2015/01/15/about-computer-graphics.html?highlight=railroad#railroad-diagrams

**Comment by DanielSiepmann** [comment]
That should be part of Fluid itself, not TYPO3 / Docs related.
Also parsing will change dramatically in the future, making things much easier.

I would vote for closing the issue.

**Comment by linawolf** [comment]
I agree with Danie
