### ISSUE TITLE
Extension documentation best practices - what to render on GitHub start page?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#91]
README.rst + README.md is by default rendered on GitHub. We propagated the use of `Documentation/Index.rst` as start page (though other [start pages are possible as well](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/DirectoryFilenames.html#supported-filenames-and-formats)).

# Problem

* extension authors often do not use our solution at all. They use only README.rst / .md on GitHub. Nothing is rendered on docs.typo3.org
* extension authors often maintain both: documentation in README.rst or README.md which is rendered on GitHub **and** a Documentation project which is rendered on docs.typo3.org. Often one of these is outdated. In any case, it is redundant and not really necessary.

Is this even a problem?

# Open questions

* Is our solution considered as too complicated? Is a 1 file solution actually better to maintain, at least for small doc projects?
* Do many people even know they can use a README.rst or README.md to be rendered on docs.typo3.org instead of a several files in a `Documentation` folder?
* Do we want to discourage other start files from `Documentation/Index.rst` or keep maintaining this?

# Possible Solutions

There are currently basically 2 approaches that can be used to **address what is rendered on GitHub when you go to start page of the repo**:

1. Add a README.rst (or README.md) to your project. There, add a link to direct people to your official manual on docs.typo3.org. The README.rst is not used as documentation. It is used as a short "about this repo" page. It directs people
to the rendered documentation on docs.typo3.org, e.g. see https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/blob/master/README.rst. The
project Read the docs does something similar
2. Use one single file without toctree for your documentation. You are already using README.md. You can continue using that or switch to README.rst. Either one will also get rendered on the docs server with latest version of the Docker image. Do away with the Documentation folder or just keep the images in there. Only use reStructuredText markup that can be rendered with TYPO3 docs rendering toolchain and GitHub. This makes maintaining your documentation a little more difficult, if your documentation is extensive. Also you cannot use some of the nifty features that we offer. It may however be the better
solution for small documentation projects. (Disclaimer: there is currently an open bug. So wait a bit or contact us on Slack #typo3-documentation before you do this)

Examples for solution 1:

* all official manuals

Examples for solution 2:

* tinymce: [source](https://gitlab.sgalinski.de/typo3/tinymce), [docs](https://docs.typo3.org/typo3cms/extensions/tinymce/stable/)

# Still open issues

Until the following are resolved, we should probably not recommend solution 2 (yet):

* [It is not possible to render a standalone README.rst / README.md with this Docker image branch1-6 only bug](https://github.com/t3docs/docker-render-documentation/issues/31) (is fixed in 2.0.0 of Docker image)
* [Open
Weird looking "duplicate" menu for start file without toctree](https://github.com/t3docs/docker-render-documentation/issues/64) (has workaround)

**Comment by alexander-nitsche** [comment]
Solution (1) is recommended in the current documentation standard [1][2] and even if you want to maintain a single file, you should probably use the README file only as portal page with abstract, badges and links, and use the Documentation/Index.rst as documentation of your project (see e.g. https://github.com/FriendsOfTYPO3/feedit).

[1] https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/FileStructure.html
[2] https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/UserRoundTrip.html

**Comment by sypets** [comment]
This is quite an old issue. I would like to close now.
